"""Aggregated FastAPI routers for the application."""

from . import (
    health,
    auth,
    ped,
    families,
    family_qc_reports,
    structural_variants,
    bed,
    chromosomes,
    genes,
    blacklist,
    segmental_duplications,
    cnvs,
    dgv,
    panels,
    projects,
    species,
    assemblies,
    admin,
    cram,
    reference,
    repeat_expansions,
    family_imports,
    product,
    hpo,
    variant_explorer,
    ui_events,
    lookups,
)

all_routers = [
    health.router,
    auth.router,
    ped.router,
    families.router,
    family_qc_reports.router,
    structural_variants.router,
    bed.router,
    chromosomes.router,
    genes.router,
    blacklist.router,
    segmental_duplications.router,
    cnvs.router,
    dgv.router,
    panels.router,
    projects.router,
    species.router,
    assemblies.router,
    admin.router,
    cram.router,
    reference.router,
    repeat_expansions.router,
    family_imports.router,
    product.router,
    hpo.router,
    variant_explorer.router,
    ui_events.router,
    lookups.router,
]

__all__ = ["all_routers"]
