from __future__ import annotations

from typing import Any


# The first repeat count of a premutation, per gene: an allele that does not cause the
# disease in its carrier but can expand to a full mutation in a child. STRchive puts it
# in its intermediate range (FMR1 45-200), with the grey zone, so it is set here. FMR1:
# normal up to 44, intermediate (grey zone) 45-54, premutation 55-200, full mutation
# above 200 (ACMG technical standards for fragile X testing).
PREMUTATION_MIN_BY_GENE: dict[str, int] = {"FMR1": 55}


# The catalogue rows every start upserts into ``repeat_loci``, next to the STRchive loci. A
# call's TRID decides which row classifies it (for FMR1, TRID "FMR1" finds the built-in row
# below and "FXS_FMR1" the STRchive one). ``warning_min`` and ``pathogenic_min`` are the
# FIRST count of the grey zone and of the pathogenic range: the classifier tests ``>=``, as
# STRchive's inclusive ranges read. A range published as "more than N" starts at N + 1.
#
# Where STRchive has the locus (every row below, today) the row carries STRchive's two
# thresholds, so a call reads the same whichever row its TRID finds (the owner's decision of
# 2026-10-09, CLIN-22). Change them together with ``STRchive-loci.json``, never apart:
# test_repeat_thresholds_follow_strchive.py fails when the two disagree. ``None`` where
# STRchive gives no such range (SCA31, BEAN1: no intermediate range).
BUILTIN_REPEAT_LOCI: list[dict[str, Any]] = [
    {
        "locus_id": "HTT",
        "gene": "HTT",
        "display_name": "HTT",
        "disease": "Huntington disease",
        "inheritance": "AD",
        "motif": "CAG",
        "warning_min": 27,
        "pathogenic_min": 36,
        "aliases": ["HD"],
    },
    {
        "locus_id": "ATXN1",
        "gene": "ATXN1",
        "display_name": "ATXN1",
        "disease": "Spinocerebellar ataxia type 1",
        "inheritance": "AD",
        "motif": "CAG",
        "warning_min": 36,
        "pathogenic_min": 39,
        "aliases": ["SCA1"],
    },
    {
        "locus_id": "ATXN2",
        "gene": "ATXN2",
        "display_name": "ATXN2",
        "disease": "Spinocerebellar ataxia type 2",
        "inheritance": "AD",
        "motif": "CAG",
        "warning_min": 29,
        "pathogenic_min": 35,
        "aliases": ["SCA2"],
    },
    {
        "locus_id": "ATXN3",
        "gene": "ATXN3",
        "display_name": "ATXN3",
        "disease": "Spinocerebellar ataxia type 3 / Machado-Joseph disease",
        "inheritance": "AD",
        "motif": "CAG",
        "warning_min": 45,
        "pathogenic_min": 60,
        "aliases": ["SCA3", "MJD"],
    },
    {
        "locus_id": "CACNA1A",
        "gene": "CACNA1A",
        "display_name": "CACNA1A",
        "disease": "Spinocerebellar ataxia type 6",
        "inheritance": "AD",
        "motif": "CAG",
        "warning_min": 19,
        "pathogenic_min": 21,
        "aliases": ["SCA6"],
    },
    {
        "locus_id": "ATXN7",
        "gene": "ATXN7",
        "display_name": "ATXN7",
        "disease": "Spinocerebellar ataxia type 7",
        "inheritance": "AD",
        "motif": "CAG",
        "warning_min": 28,
        "pathogenic_min": 37,
        "aliases": ["SCA7"],
    },
    {
        "locus_id": "TBP",
        "gene": "TBP",
        "display_name": "TBP",
        "disease": "Spinocerebellar ataxia type 17",
        "inheritance": "AD",
        "motif": "CAG",
        "warning_min": 41,
        "pathogenic_min": 49,
        "aliases": ["SCA17"],
    },
    {
        "locus_id": "ATN1",
        "gene": "ATN1",
        "display_name": "ATN1",
        "disease": "Dentatorubral-pallidoluysian atrophy",
        "inheritance": "AD",
        "motif": "CAG",
        "warning_min": 36,
        "pathogenic_min": 48,
        "aliases": ["DRPLA"],
    },
    {
        "locus_id": "AR",
        "gene": "AR",
        "display_name": "AR",
        "disease": "Spinal and bulbar muscular atrophy",
        "inheritance": "X-linked",
        "motif": "CAG",
        "warning_min": 36,
        "pathogenic_min": 38,
        "x_linked": True,
        "aliases": ["SBMA", "Kennedy disease"],
    },
    {
        "locus_id": "FMR1",
        "gene": "FMR1",
        "display_name": "FMR1",
        "disease": "Fragile X syndrome",
        "inheritance": "X-linked",
        "motif": "CGG",
        "warning_min": 45,
        # A full mutation is more than 200 repeats; 55-200 is a premutation (STRchive 201).
        "pathogenic_min": 201,
        "x_linked": True,
        "aliases": ["Fragile X"],
    },
    {
        "locus_id": "DMPK",
        "gene": "DMPK",
        "display_name": "DMPK",
        "disease": "Myotonic dystrophy type 1",
        "inheritance": "AD",
        "motif": "CTG",
        "warning_min": 35,
        "pathogenic_min": 50,
        "aliases": ["DM1"],
    },
    {
        "locus_id": "ATXN8OS",
        "gene": "ATXN8OS",
        "display_name": "ATXN8OS / ATXN8",
        "disease": "Spinocerebellar ataxia type 8",
        "inheritance": "AD",
        "motif": "CTG",
        "warning_min": 50,
        "pathogenic_min": 71,
        "aliases": ["SCA8", "ATXN8"],
    },
    {
        "locus_id": "CNBP",
        "gene": "CNBP",
        "display_name": "CNBP / ZNF9",
        "disease": "Myotonic dystrophy type 2",
        "inheritance": "AD",
        "motif": "CCTG",
        "warning_min": 27,
        "pathogenic_min": 75,
        "aliases": ["ZNF9", "DM2"],
    },
    {
        "locus_id": "FXN",
        "gene": "FXN",
        "display_name": "FXN",
        "disease": "Friedreich ataxia",
        "inheritance": "AR",
        "motif": "GAA",
        "warning_min": 34,
        "pathogenic_min": 56,
        "aliases": [],
    },
    {
        "locus_id": "C9orf72",
        "gene": "C9orf72",
        "display_name": "C9orf72",
        "disease": "C9orf72-related ALS / frontotemporal dementia",
        "inheritance": "AD",
        "motif": "GGGGCC",
        "warning_min": 24,
        "pathogenic_min": 31,
        "aliases": ["ALS-FTD"],
    },
    {
        "locus_id": "ATXN10",
        "gene": "ATXN10",
        "display_name": "ATXN10",
        "disease": "Spinocerebellar ataxia type 10",
        "inheritance": "AD",
        "motif": "ATTCT",
        "warning_min": 33,
        "pathogenic_min": 800,
        "aliases": ["SCA10"],
    },
    {
        "locus_id": "BEAN1",
        "gene": "BEAN1",
        "display_name": "BEAN1 / TK2 region",
        "disease": "Spinocerebellar ataxia type 31",
        "inheritance": "AD",
        "motif": "TGGAA",
        "warning_min": None,
        "pathogenic_min": 110,
        "aliases": ["SCA31", "TK2"],
    },
    {
        "locus_id": "PPP2R2B",
        "gene": "PPP2R2B",
        "display_name": "PPP2R2B",
        "disease": "Spinocerebellar ataxia type 12",
        "inheritance": "AD",
        "motif": "CAG",
        "warning_min": 40,
        "pathogenic_min": 51,
        "aliases": ["SCA12"],
    },
    {
        "locus_id": "NOP56",
        "gene": "NOP56",
        "display_name": "NOP56",
        "disease": "Spinocerebellar ataxia type 36",
        "inheritance": "AD",
        "motif": "GGCCTG",
        "warning_min": 15,
        "pathogenic_min": 650,
        "aliases": ["SCA36"],
    },
    {
        "locus_id": "JPH3",
        "gene": "JPH3",
        "display_name": "JPH3",
        "disease": "Huntington disease-like 2",
        "inheritance": "AD",
        "motif": "CTG",
        "warning_min": 29,
        "pathogenic_min": 40,
        "aliases": ["HDL2"],
    },
    {
        "locus_id": "PABPN1",
        "gene": "PABPN1",
        "display_name": "PABPN1",
        "disease": "Oculopharyngeal muscular dystrophy",
        "inheritance": "AD",
        "motif": "GCN",
        "warning_min": 11,
        "pathogenic_min": 12,
        "aliases": ["OPMD"],
    },
]
