from __future__ import annotations

from typing import Any


BUILTIN_REPEAT_LOCI: list[dict[str, Any]] = [
    {
        "locus_id": "HTT",
        "gene": "HTT",
        "display_name": "HTT",
        "disease": "Huntington disease",
        "inheritance": "AD",
        "motif": "CAG",
        "warning_min": 27,
        "pathogenic_min": 36,
        "aliases": ["HD"],
    },
    {
        "locus_id": "ATXN1",
        "gene": "ATXN1",
        "display_name": "ATXN1",
        "disease": "Spinocerebellar ataxia type 1",
        "inheritance": "AD",
        "motif": "CAG",
        "warning_min": 39,
        "pathogenic_min": 45,
        "aliases": ["SCA1"],
    },
    {
        "locus_id": "ATXN2",
        "gene": "ATXN2",
        "display_name": "ATXN2",
        "disease": "Spinocerebellar ataxia type 2",
        "inheritance": "AD",
        "motif": "CAG",
        "warning_min": 32,
        "pathogenic_min": 34,
        "aliases": ["SCA2"],
    },
    {
        "locus_id": "ATXN3",
        "gene": "ATXN3",
        "display_name": "ATXN3",
        "disease": "Spinocerebellar ataxia type 3 / Machado-Joseph disease",
        "inheritance": "AD",
        "motif": "CAG",
        "warning_min": 45,
        "pathogenic_min": 60,
        "aliases": ["SCA3", "MJD"],
    },
    {
        "locus_id": "CACNA1A",
        "gene": "CACNA1A",
        "display_name": "CACNA1A",
        "disease": "Spinocerebellar ataxia type 6",
        "inheritance": "AD",
        "motif": "CAG",
        "warning_min": 19,
        "pathogenic_min": 20,
        "aliases": ["SCA6"],
    },
    {
        "locus_id": "ATXN7",
        "gene": "ATXN7",
        "display_name": "ATXN7",
        "disease": "Spinocerebellar ataxia type 7",
        "inheritance": "AD",
        "motif": "CAG",
        "warning_min": 20,
        "pathogenic_min": 36,
        "aliases": ["SCA7"],
    },
    {
        "locus_id": "TBP",
        "gene": "TBP",
        "display_name": "TBP",
        "disease": "Spinocerebellar ataxia type 17",
        "inheritance": "AD",
        "motif": "CAG",
        "warning_min": 42,
        "pathogenic_min": 49,
        "aliases": ["SCA17"],
    },
    {
        "locus_id": "ATN1",
        "gene": "ATN1",
        "display_name": "ATN1",
        "disease": "Dentatorubral-pallidoluysian atrophy",
        "inheritance": "AD",
        "motif": "CAG",
        "warning_min": 36,
        "pathogenic_min": 48,
        "aliases": ["DRPLA"],
    },
    {
        "locus_id": "AR",
        "gene": "AR",
        "display_name": "AR",
        "disease": "Spinal and bulbar muscular atrophy",
        "inheritance": "X-linked",
        "motif": "CAG",
        "warning_min": 36,
        "pathogenic_min": 38,
        "x_linked": True,
        "aliases": ["SBMA", "Kennedy disease"],
    },
    {
        "locus_id": "FMR1",
        "gene": "FMR1",
        "display_name": "FMR1",
        "disease": "Fragile X syndrome",
        "inheritance": "X-linked",
        "motif": "CGG",
        "warning_min": 45,
        "pathogenic_min": 200,
        "x_linked": True,
        "aliases": ["Fragile X"],
    },
    {
        "locus_id": "DMPK",
        "gene": "DMPK",
        "display_name": "DMPK",
        "disease": "Myotonic dystrophy type 1",
        "inheritance": "AD",
        "motif": "CTG",
        "warning_min": 35,
        "pathogenic_min": 50,
        "aliases": ["DM1"],
    },
    {
        "locus_id": "ATXN8OS",
        "gene": "ATXN8OS",
        "display_name": "ATXN8OS / ATXN8",
        "disease": "Spinocerebellar ataxia type 8",
        "inheritance": "AD",
        "motif": "CTG",
        "warning_min": 50,
        "pathogenic_min": 80,
        "aliases": ["SCA8", "ATXN8"],
    },
    {
        "locus_id": "CNBP",
        "gene": "CNBP",
        "display_name": "CNBP / ZNF9",
        "disease": "Myotonic dystrophy type 2",
        "inheritance": "AD",
        "motif": "CCTG",
        "warning_min": 55,
        "pathogenic_min": 75,
        "aliases": ["ZNF9", "DM2"],
    },
    {
        "locus_id": "FXN",
        "gene": "FXN",
        "display_name": "FXN",
        "disease": "Friedreich ataxia",
        "inheritance": "AR",
        "motif": "GAA",
        "warning_min": 34,
        "pathogenic_min": 66,
        "aliases": [],
    },
    {
        "locus_id": "C9orf72",
        "gene": "C9orf72",
        "display_name": "C9orf72",
        "disease": "C9orf72-related ALS / frontotemporal dementia",
        "inheritance": "AD",
        "motif": "GGGGCC",
        "warning_min": 24,
        "pathogenic_min": 30,
        "aliases": ["ALS-FTD"],
    },
    {
        "locus_id": "ATXN10",
        "gene": "ATXN10",
        "display_name": "ATXN10",
        "disease": "Spinocerebellar ataxia type 10",
        "inheritance": "AD",
        "motif": "ATTCT",
        "warning_min": 280,
        "pathogenic_min": 800,
        "aliases": ["SCA10"],
    },
    {
        "locus_id": "BEAN1",
        "gene": "BEAN1",
        "display_name": "BEAN1 / TK2 region",
        "disease": "Spinocerebellar ataxia type 31",
        "inheritance": "AD",
        "motif": "TGGAA",
        "warning_min": 300,
        "pathogenic_min": 500,
        "aliases": ["SCA31", "TK2"],
    },
    {
        "locus_id": "PPP2R2B",
        "gene": "PPP2R2B",
        "display_name": "PPP2R2B",
        "disease": "Spinocerebellar ataxia type 12",
        "inheritance": "AD",
        "motif": "CAG",
        "warning_min": 44,
        "pathogenic_min": 51,
        "aliases": ["SCA12"],
    },
    {
        "locus_id": "NOP56",
        "gene": "NOP56",
        "display_name": "NOP56",
        "disease": "Spinocerebellar ataxia type 36",
        "inheritance": "AD",
        "motif": "GGCCTG",
        "warning_min": 31,
        "pathogenic_min": 650,
        "aliases": ["SCA36"],
    },
    {
        "locus_id": "JPH3",
        "gene": "JPH3",
        "display_name": "JPH3",
        "disease": "Huntington disease-like 2",
        "inheritance": "AD",
        "motif": "CTG",
        "warning_min": 36,
        "pathogenic_min": 41,
        "aliases": ["HDL2"],
    },
    {
        "locus_id": "PABPN1",
        "gene": "PABPN1",
        "display_name": "PABPN1",
        "disease": "Oculopharyngeal muscular dystrophy",
        "inheritance": "AD",
        "motif": "GCN",
        "warning_min": 11,
        "pathogenic_min": 13,
        "aliases": ["OPMD"],
    },
]
