#!/usr/bin/env python3
"""Generate the frontend's API types from the backend's OpenAPI schema (#528).

Writes frontend/src/lib/apiSchema.generated.ts: one TypeScript type per schema in
components/schemas, the shapes the backend actually serves. With --check it writes
nothing and exits 1 when the file is out of date, which is how CI keeps the frontend's
types from drifting from the backend.

    python scripts/generate-api-types.py          # regenerate
    python scripts/generate-api-types.py --check  # CI: fail if stale

A response carries every field of its model: Pydantic serialises the ones with a default
too, but the schema lists only the others as required. So in a schema only responses use,
every property is typed as present; in a schema a request uses, the schema's own
`required` holds, as the client may leave the rest out. (An endpoint that drops None
values from its response, such as the SV track, does not carry those fields.) FastAPI's
own 422 error entries are not serialised from a model: `ctx` comes with some errors
only, so `ValidationError` keeps the schema's `required` too.

The schema depends on the FastAPI and Pydantic versions (FastAPI 0.141 added `input` and
`ctx` to `ValidationError`), so generate in the backend's environment, installed from
backend/requirements-dev.txt as CI does. With other versions the script warns, and a
`--check` that passes there can fail in CI.

Only the JSON-Schema forms the backend's schema uses are supported (plain types, arrays,
objects with properties or additionalProperties, anyOf/oneOf/allOf, enum, const, $ref);
anything else raises, so a new form cannot be generated wrongly without notice.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "frontend" / "src" / "lib" / "apiSchema.generated.ts"

HEADER = """\
// Generated by scripts/generate-api-types.py from the backend's OpenAPI schema (#528).
// Do not edit: change the backend's Pydantic models and regenerate. CI fails when this
// file is out of date (`python scripts/generate-api-types.py --check`).
"""

IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")
# Built by FastAPI rather than serialised from a model: only their `required` is certain.
FRAMEWORK_SCHEMAS = {"ValidationError"}
# The packages whose version shapes the schema, as backend/requirements.txt pins them.
SCHEMA_PACKAGES = ("fastapi", "pydantic")
REQUIREMENTS = ROOT / "backend" / "requirements.txt"
KNOWN_KEYS = {
    "type", "properties", "required", "items", "additionalProperties", "anyOf", "oneOf", "allOf",
    "enum", "const", "$ref", "title", "description", "default", "format", "examples", "example",
    "minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum", "minLength", "maxLength",
    "pattern", "minItems", "maxItems", "uniqueItems", "deprecated", "readOnly", "writeOnly",
    "contentMediaType", "contentEncoding",
}


def load_schema() -> dict:
    os.environ.setdefault("APP_ENV", "test")
    sys.path.insert(0, str(ROOT))
    from backend.app.main import app  # noqa: E402 - needs the env and path above

    return app.openapi()


def version_mismatches() -> list[str]:
    """The schema-shaping packages whose running version is not the one the backend pins."""
    import fastapi
    import pydantic

    running = {"fastapi": fastapi.__version__, "pydantic": pydantic.VERSION}
    pinned = {}
    for line in REQUIREMENTS.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^([A-Za-z0-9_.-]+)==([^\s\\;]+)", line.strip())
        if match and match.group(1).lower() in SCHEMA_PACKAGES:
            pinned[match.group(1).lower()] = match.group(2)
    return [
        f"{package} {running[package]} (backend/requirements.txt pins {pinned[package]})"
        for package in SCHEMA_PACKAGES
        if package in pinned and running[package] != pinned[package]
    ]


def type_name(name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_$]", "_", name)
    return cleaned if IDENTIFIER.match(cleaned) and not cleaned[0].isdigit() else f"_{cleaned}"


def literal(value) -> str:
    return json.dumps(value, ensure_ascii=False)


def union(parts: list[str]) -> str:
    seen: list[str] = []
    for part in parts:
        if part not in seen:
            seen.append(part)
    return " | ".join(seen) if seen else "never"


def wrap(ts: str) -> str:
    return f"({ts})" if (" | " in ts or " & " in ts) else ts


def doc(text: str | None, indent: str) -> list[str]:
    if not text:
        return []
    lines = text.replace("*/", "* /").strip().splitlines()
    if len(lines) == 1:
        return [f"{indent}/** {lines[0].strip()} */"]
    return [f"{indent}/**", *(f"{indent} * {line.rstrip()}".rstrip() for line in lines), f"{indent} */"]


def refs(node, found: set[str]) -> set[str]:
    """Every schema name a node refers to, directly or through other schemas' refs."""
    if isinstance(node, dict):
        if "$ref" in node:
            found.add(node["$ref"].rsplit("/", 1)[-1])
        for value in node.values():
            refs(value, found)
    elif isinstance(node, list):
        for value in node:
            refs(value, found)
    return found


def closure(names: set[str], schemas: dict) -> set[str]:
    pending, seen = list(names), set()
    while pending:
        name = pending.pop()
        if name in seen or name not in schemas:
            continue
        seen.add(name)
        pending.extend(refs(schemas[name], set()) - seen)
    return seen


def request_schemas(spec: dict) -> set[str]:
    """The schemas a request can carry: request bodies and parameters, and what they use."""
    direct: set[str] = set()
    for methods in spec.get("paths", {}).values():
        for operation in methods.values():
            if not isinstance(operation, dict):
                continue
            refs(operation.get("requestBody", {}), direct)
            refs(operation.get("parameters", []), direct)
    return closure(direct, spec.get("components", {}).get("schemas", {}))


# Set per schema while generating: whether every property is present (a response schema).
ALL_PRESENT = False


def ts_type(node: dict, indent: str = "") -> str:
    unknown = set(node) - KNOWN_KEYS
    if unknown:
        raise ValueError(f"unsupported schema keys {sorted(unknown)} in {node}")
    if "$ref" in node:
        return type_name(node["$ref"].rsplit("/", 1)[-1])
    if "const" in node:
        return literal(node["const"])
    if "enum" in node:
        return union([literal(value) for value in node["enum"]])
    for key in ("anyOf", "oneOf"):
        if key in node:
            return union([ts_type(part, indent) for part in node[key]])
    if "allOf" in node:
        parts = [ts_type(part, indent) for part in node["allOf"]]
        return parts[0] if len(parts) == 1 else " & ".join(wrap(part) for part in parts)
    kind = node.get("type")
    if isinstance(kind, list):
        return union([ts_type({**node, "type": item}, indent) for item in kind])
    if kind == "string":
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        return f"{wrap(ts_type(node['items'], indent))}[]" if "items" in node else "unknown[]"
    if kind == "object" or "properties" in node:
        return object_type(node, indent)
    if kind is None:
        return "unknown"
    raise ValueError(f"unsupported type {kind!r}")


def object_type(node: dict, indent: str) -> str:
    properties = node.get("properties") or {}
    extra = node.get("additionalProperties")
    if not properties:
        if extra is False:
            return "Record<string, never>"
        value = "unknown" if extra in (None, True) else ts_type(extra, indent)
        return f"Record<string, {value}>"
    required = set(node.get("required") or [])
    if ALL_PRESENT:
        required = set(properties)
    inner = indent + "  "
    lines = ["{"]
    for prop, schema in properties.items():
        key = prop if IDENTIFIER.match(prop) else literal(prop)
        optional = "" if prop in required else "?"
        lines.extend(doc(schema.get("description"), inner))
        lines.append(f"{inner}{key}{optional}: {ts_type(schema, inner)};")
    if extra not in (None, False):
        value = "unknown" if extra is True else ts_type(extra, inner)
        lines.append(f"{inner}[key: string]: {value};")
    lines.append(f"{indent}}}")
    return "\n".join(lines)


def generate(spec: dict) -> str:
    global ALL_PRESENT
    schemas = spec.get("components", {}).get("schemas", {})
    in_requests = request_schemas(spec)
    out = [HEADER]
    for name in sorted(schemas):
        schema = schemas[name]
        ALL_PRESENT = name not in in_requests and name not in FRAMEWORK_SCHEMAS
        out.extend(doc(schema.get("description"), ""))
        body = ts_type(schema)
        if body.startswith("{"):
            out.append(f"export interface {type_name(name)} {body}")
        else:
            out.append(f"export type {type_name(name)} = {body};")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    text = generate(load_schema())
    mismatches = version_mismatches()
    if mismatches:
        print(
            "warning: the schema depends on these versions, which differ from the backend's: "
            + "; ".join(mismatches)
            + ". Install backend/requirements-dev.txt, as CI does.",
            file=sys.stderr,
        )
    if "--check" in sys.argv[1:]:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(
                f"{OUTPUT.relative_to(ROOT)} is out of date with the backend's OpenAPI schema.\n"
                "Run: python scripts/generate-api-types.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is up to date.")
        return 0
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
