// Generated by scripts/generate-api-types.py from the backend's OpenAPI schema (#528).
// Do not edit: change the backend's Pydantic models and regenerate. CI fails when this
// file is out of date (`python scripts/generate-api-types.py --check`).

export interface AcmgClassificationPayload {
  criteria?: AcmgCriterionSelection[];
  point_total?: number | null;
  classification?: string | null;
  vus_tier?: string | null;
}

export interface AcmgCriterionSelection {
  code: string;
  strength: string;
  accepted?: boolean;
  evidence?: string | null;
  auto_suggested?: boolean;
}

export interface AlignmentManifestEntryOut {
  sample_id: string;
  format: "bam" | "cram";
  url: string;
  index_url: string;
}

/** The annotation/reference version manifest for a family (report provenance). */
export interface AnnotationManifestOut {
  family_id: string;
  assembly: string | null;
  source: string | null;
  recorded_at: string | null;
  recorded_by: string | null;
  modules: AnnotationModuleOut[];
}

/** Record/override a family's upstream annotation module versions. */
export interface AnnotationManifestUpdate {
  modules?: Record<string, unknown>;
  source?: string | null;
}

/** One annotation/reference module and the version that backed the data. */
export interface AnnotationModuleOut {
  key: string;
  label: string;
  version: string | null;
  detail: string | null;
  layer: string;
  by_modality: Record<string, string> | null;
}

export interface AssemblyCreate {
  species_id: string;
  assembly_name: string;
  version: string;
  release_date: string;
}

export interface AssemblyOut {
  _id: string;
  species_id: string;
  assembly_name: string;
  version: string;
  release_date: string;
}

export interface AssemblyReferenceStatusOut {
  assembly_id: string;
  assembly_name: string;
  chromosomes: number;
  genes: number;
  blacklist_regions: number;
  clinical_cnvs: number;
  segmental_duplications: number;
  dgv: number;
  last_imports: ReferenceDatasetImportOut[];
}

export interface AuditLogEventOut {
  id: string;
  created_at: string;
  user_id: string | null;
  user_email: string | null;
  user_role: string | null;
  method: string;
  route_path: string | null;
  path: string;
  query_string: string | null;
  status_code: number;
  duration_ms: number;
  remote_ip: string | null;
  user_agent: string | null;
  referer: string | null;
  protocol: string | null;
  request_body: unknown | null;
  request_meta: Record<string, unknown>;
  db_update: Record<string, unknown> | null;
  error: string | null;
}

export interface AuditLogPageOut {
  page: number;
  page_size: number;
  total: number;
  items: AuditLogEventOut[];
}

export interface BlacklistRegionOut {
  _id: string;
  chr: string;
  start: number;
  end: number;
  label: string;
}

export interface Body_import_nipt_artifacts_endpoint_api_admin_nipt_artifacts_import_post {
  file: string;
  assembly_id: string;
  assay_key?: string;
}

export interface Body_token_api_auth_token_post {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
}

export interface Body_upload_bed_api_bed_upload__sample_id___bed_type__post {
  file: string;
}

export interface Body_upload_family_small_variants_api_families__family_id__small_variants_upload_post {
  file: string;
}

export interface Body_upload_ped_api_ped_upload_post {
  file: string;
  roi_query?: string | null;
  inheritance_model?: string | null;
  obligate_carriers?: string | null;
  proven_carriers?: string | null;
}

export interface Body_upload_reference_data_api_assemblies__assembly_id__reference_upload__dataset_type__post {
  file: string;
}

export interface Body_upload_repeat_expansions_api_repeat_expansions_upload__sample_id__post {
  file: string;
}

export interface Body_upload_structural_variants_api_structural_variants_upload__sample_id__post {
  file: string;
}

export interface ChromosomeOut {
  _id: string;
  assembly_id: string;
  chr: string;
  size: number;
  bands: IdeogramBandOut[];
}

export interface ChromosomeSizeOut {
  chr: string;
  size: number;
}

/** A classification whose backing annotation changed since it was made. */
export interface ClassificationDriftItem {
  variant_id: string;
  acmg_class: string | null;
  classified_by: string | null;
  classified_at: string | null;
  status: string;
  annotation_version_from: string | null;
  annotation_version_to: string | null;
  clinvar_from: string | null;
  clinvar_to: string | null;
}

/**
 * Evidence-drift summary for a family's ACMG classifications: the small variants at
 * the top level, the structural variants and CNVs under ``structural``.
 */
export interface ClassificationDriftOut {
  family_id: string;
  checked: number;
  drifted_count: number;
  drifted: ClassificationDriftItem[];
  structural: StructuralClassificationDriftOut;
}

export interface ClickHouseDetachedPartOut {
  table: string;
  reason: string;
  count: number;
}

export interface ClickHouseGeneIndexConsistencyOut {
  checked: boolean;
  gene_index_keys: number;
  annotation_index_gene_keys: number;
  consistent: boolean;
  drift: number;
}

/** The scheduled ClickHouse integrity check, as the running server last saw it. */
export interface ClickHouseIntegrityMonitorOut {
  enabled: boolean;
  interval_seconds: number;
  last_sweep_at: string | null;
  last_sweep_error: string | null;
  results: ClickHouseIntegrityMonitorResultOut[];
}

/** The scheduled integrity check's last result for one assembly. */
export interface ClickHouseIntegrityMonitorResultOut {
  assembly_name: string;
  checked_at: string;
  report: ClickHouseVariantIntegrityOut | null;
  error: string | null;
}

export interface ClickHouseVariantAssemblyListOut {
  assemblies: ClickHouseVariantAssemblyStatusOut[];
}

export interface ClickHouseVariantAssemblyStatusOut {
  assembly_name: string;
  health: string;
  expected_table_count: number;
  existing_table_count: number;
  missing_tables: string[];
  pending_mutations: number;
  total_rows: number;
  total_bytes_on_disk: number;
  small_variant_rows: number;
  structural_variant_rows: number;
  tables: ClickHouseVariantTableStatusOut[];
}

export interface ClickHouseVariantIntegrityOut {
  assembly_name: string;
  status: string;
  table_checks: ClickHouseVariantTableCheckOut[];
  detached_broken_parts: ClickHouseDetachedPartOut[];
  gene_index_consistency: ClickHouseGeneIndexConsistencyOut;
  notes: string[];
}

export interface ClickHouseVariantTableCheckOut {
  name: string;
  exists: boolean;
  passed: boolean | null;
  failed_parts: number;
  messages: string[];
}

export interface ClickHouseVariantTableStatusOut {
  name: string;
  variant_type: string;
  kind: string;
  exists: boolean;
  engine: string | null;
  row_count: number;
  bytes_on_disk: number;
  pending_mutations: number;
}

/** One immutable clinical action (who did what, when, before -> after). */
export interface ClinicalAuditEventOut {
  id: string;
  created_at: string;
  variant_id: string | null;
  actor: string;
  action: string;
  summary: string | null;
  before: Record<string, unknown> | null;
  after: Record<string, unknown> | null;
}

/** A family's clinical audit timeline (most recent first). */
export interface ClinicalAuditOut {
  family_id: string;
  events: ClinicalAuditEventOut[];
}

export interface ClinicalCnvKbJobOut {
  _id: string;
  assembly_id: string;
  assembly_name: string;
  status: "queued" | "running" | "completed" | "failed";
  skip_clinvar: boolean;
  requested_by: string | null;
  requested_at: string;
  started_at: string | null;
  completed_at: string | null;
  inserted: number;
  error: string | null;
}

export interface ClinicalCnvKbRebuildRequest {
  assembly: string;
  skip_clinvar?: boolean;
}

export interface ClinicalCnvKbStatusOut {
  active_job: ClinicalCnvKbJobOut | null;
  recent_jobs: ClinicalCnvKbJobOut[];
  available: boolean;
  detail: string | null;
}

export interface ClinicalCnvOut {
  _id: string;
  chr: string;
  start: number;
  end: number;
  type: string | null;
  label: string;
  details_html: string | null;
  assembly: string | null;
  omim_id: string | null;
  omim_title: string | null;
  decipher_id: string | null;
  description: string | null;
  cytoband: string | null;
  source_id: string | null;
  orpha_id: string | null;
  orpha_name: string | null;
  clinvar_pathogenic_loss_count: number | null;
  clinvar_pathogenic_gain_count: number | null;
  clinvar_pathogenic_accessions: string[] | null;
}

/** ClinGen 2019 copy-number classification (structural variants only). */
export interface CnvAcmgClassificationPayload {
  kind?: "loss" | "gain";
  criteria?: CnvAcmgCriterion[];
  point_total?: number | null;
  classification?: string | null;
}

export interface CnvAcmgCriterion {
  code: string;
  points?: number;
  accepted?: boolean;
  evidence?: string | null;
  auto_suggested?: boolean;
}

export interface DgvDensityBin {
  start: number;
  end: number;
  gain: number;
  loss: number;
  mixed: number;
  other: number;
}

/**
 * DGV is too dense to draw every variant at chromosome scale. The server
 * decides per request: `lines` (individual variants, when the in-view count is
 * small) or `density` (per-bin gain/loss/mixed counts, when it is large).
 */
export interface DgvTrackOut {
  total: number;
  mode: "lines" | "density";
  bin_size: number;
  variants: DgvVariantOut[];
  bins: DgvDensityBin[];
}

export interface DgvVariantOut {
  chr: string;
  start: number;
  end: number;
  accession: string | null;
  variant_type: string | null;
  variant_subtype: string | null;
  variant_class: string;
  frequency: number | null;
  observed_gains: number | null;
  observed_losses: number | null;
  source: string | null;
}

/**
 * When a dataset's import ran and how far it got. ``fraction_read`` is the share of
 * its input files' bytes read (of a gzip file, the compressed bytes), measured at
 * ``measured_at``, by an importer that reports it; ``seconds_left`` is the time it should
 * still take at that moment, at the pace it has read so far, and None until there is
 * enough of a pace to tell.
 */
export interface FamilyImportDatasetProgress {
  started_at: string;
  finished_at: string | null;
  measured_at: string | null;
  fraction_read: number | null;
  seconds_left: number | null;
}

export interface FamilyImportDatasetSummary {
  dataset_type: string;
  enabled: boolean;
  status: "pending" | "valid" | "warning" | "error" | "disabled" | "skipped" | "running" | "registered" | "imported" | "failed";
  files: string[];
  samples: string[];
  message: string | null;
  summary: Record<string, unknown>;
  progress: FamilyImportDatasetProgress | null;
}

export interface FamilyImportValidationIssue {
  code: string;
  message: string;
  dataset: string | null;
  sample_id: string | null;
  path: string | null;
}

export interface FamilyInventoryDetailOut {
  family_id: string;
  metadata: Record<string, unknown>;
  projects: string[];
  sample_count: number;
  track_counts: Record<string, number>;
  total_records: number;
  samples: SampleInventoryOut[];
}

export interface FamilyInventoryPageOut {
  total: number;
  page: number;
  page_size: number;
  items: FamilyInventorySummaryOut[];
}

export interface FamilyInventorySummaryOut {
  family_id: string;
  metadata: Record<string, unknown>;
  projects: string[];
  sample_count: number;
  track_counts: Record<string, number>;
  total_records: number;
}

export interface FamilyManifestDatasetAvailability {
  dataset_type: string;
  enabled: boolean;
  complete: boolean;
  files: FamilyManifestFileAvailability[];
  samples: string[];
  message: string | null;
}

export interface FamilyManifestFileAvailability {
  role: string;
  path: string;
  exists: boolean;
  sample_id: string | null;
}

export interface FamilyMemberBatchUpdate {
  expected_structure_version?: number | null;
  change_reason?: string | null;
  updates?: FamilyMemberBatchUpdateItem[];
}

export interface FamilyMemberBatchUpdateItem {
  sample_id: string;
  new_sample_id?: string | null;
  sex?: "male" | "female" | "und" | null;
  role?: "proband" | "father" | "mother" | "sibling" | "embryo" | "relative" | null;
  clinical_status?: "unknown" | "unaffected" | "affected" | null;
  carrier_status?: "unknown" | "not_carrier" | "carrier" | null;
  carrier_type?: "obligate" | "proven" | "reported" | "inferred" | null;
  father_id?: string | null;
  mother_id?: string | null;
}

export interface FamilyMemberBatchUpdateOut {
  family: FamilyOut;
  warnings: string[];
  stale_analysis_scopes: string[];
  data_counts: Record<string, number>;
  cleared_data_counts: Record<string, number>;
}

export interface FamilyMemberDeleteOut {
  family: FamilyOut;
  warnings: string[];
  stale_analysis_scopes: string[];
  data_counts: Record<string, number>;
  cleared_data_counts: Record<string, number>;
  impact: FamilyMemberImpactOut;
}

export interface FamilyMemberDetailOut {
  member: FamilyMemberOut;
  father_id: string | null;
  mother_id: string | null;
  hpo_annotations: HpoAnnotationOut[];
  impact: FamilyMemberImpactOut;
}

export interface FamilyMemberImpactOut {
  sample_id: string;
  pedigree_references: Record<string, number>;
  data_counts: Record<string, number>;
  affected_analysis_scopes: string[];
  stale_analysis_scopes: string[];
  warnings: string[];
  destructive: boolean;
  requires_manual_recalculation: boolean;
}

/** Schema for a family member with a human-friendly sample ID. */
export interface FamilyMemberOut {
  sample_id: string;
  role: "proband" | "father" | "mother" | "sibling" | "embryo" | "relative";
  affected: boolean;
  sex: "male" | "female" | "und";
  clinical_status: "unknown" | "unaffected" | "affected";
  carrier_status: "unknown" | "not_carrier" | "carrier";
  carrier_type: "obligate" | "proven" | "reported" | "inferred" | null;
  carrier_evidence: Record<string, unknown>;
  active: boolean;
  sample_metadata: Record<string, unknown>;
  sequencing_qc: SampleSequencingQcEvaluationOut | null;
}

export interface FamilyMemberUpdate {
  sample_id?: string | null;
  sex?: "male" | "female" | "und" | null;
  role?: "proband" | "father" | "mother" | "sibling" | "embryo" | "relative" | null;
  clinical_status?: "unknown" | "unaffected" | "affected" | null;
  carrier_status?: "unknown" | "not_carrier" | "carrier" | null;
  carrier_type?: "obligate" | "proven" | "reported" | "inferred" | null;
  father_id?: string | null;
  mother_id?: string | null;
  expected_structure_version?: number | null;
  clear_existing_genomic_data?: boolean;
  change_reason?: string | null;
}

export interface FamilyMemberUpdateOut {
  family: FamilyOut;
  warnings: string[];
  stale_analysis_scopes: string[];
  data_counts: Record<string, number>;
  cleared_data_counts: Record<string, number>;
  member: FamilyMemberOut;
  father_id: string | null;
  mother_id: string | null;
  impact: FamilyMemberImpactOut;
}

/**
 * Partial update of a family's workflow metadata.
 *
 * Only the fields actually present in the request body are applied (tracked
 * via ``model_fields_set``); a field sent explicitly as ``null`` clears it.
 */
export interface FamilyMetadataUpdate {
  status_key?: string | null;
  assigned_to?: string | null;
  reviewed_by?: string | null;
}

export interface FamilyMitoDNAAnalysisOut {
  samples: MitoDNASampleOut[];
  variants: MitoDNAVariantOut[];
  structural_variants: MitoDNAStructuralVariantOut[];
  variant_count: number;
  has_coverage: boolean;
  qc_notes: string[];
  heteroplasmy_threshold: number;
  homoplasmy_threshold: number;
}

/** Schema for families returned by the API. */
export interface FamilyOut {
  _id: string;
  family_id: string;
  created_at: string;
  members: FamilyMemberOut[];
  relationships: FamilyRelationshipOut[];
  structure_version: FamilyStructureVersionOut | null;
  pedigree: string | null;
  roi: FamilyRegionOfInterestOut | null;
  projects: string[];
  status: FamilyStatusRef | null;
  assigned_to: UserRefOut | null;
  reviewed_by: UserRefOut | null;
  metadata: Record<string, unknown>;
}

/** A family package discovered under the configured import roots. */
export interface FamilyPackageCandidateOut {
  folder_path: string;
  name: string;
  family_id: string;
  has_manifest: boolean;
  has_ped: boolean;
  analysis_type: string | null;
}

export interface FamilyPackageImportCreate {
  folder_path: string;
  project_id?: string | null;
  dry_run?: boolean;
  family_id?: string | null;
  conflict_mode?: "cancel" | "update" | "overwrite";
}

export interface FamilyPackageImportJobOut {
  _id: string;
  submitted_path: string;
  family_id: string | null;
  project_id: string | null;
  status: "queued" | "validating" | "running" | "completed" | "failed";
  dry_run: boolean;
  worker_id: string | null;
  requested_by: string;
  requested_at: string;
  started_at: string | null;
  heartbeat_at: string | null;
  completed_at: string | null;
  validation_errors: FamilyImportValidationIssue[];
  validation_warnings: FamilyImportValidationIssue[];
  logs: string[];
  datasets: FamilyImportDatasetSummary[];
  metadata: Record<string, unknown>;
  error: string | null;
}

export interface FamilyPackageManifestBuildOut {
  valid: boolean;
  family_id: string | null;
  ped_path: string | null;
  manifest_path: string;
  naming_scheme: string;
  sample_ids: string[];
  manifest_yaml: string;
  datasets: FamilyManifestDatasetAvailability[];
  errors: FamilyImportValidationIssue[];
  warnings: FamilyImportValidationIssue[];
  metadata: Record<string, unknown>;
}

export interface FamilyPackageManifestBuildRequest {
  folder_path: string;
  ped_path?: string | null;
  family_id?: string | null;
  naming_scheme?: string;
  hpo_terms?: string[];
  notes?: string | null;
}

export interface FamilyPackageManifestWriteOut {
  manifest_path: string;
  validation: FamilyPackageValidationOut;
}

export interface FamilyPackageManifestWriteRequest {
  folder_path: string;
  manifest_yaml: string;
  overwrite?: boolean;
  family_id?: string | null;
}

export interface FamilyPackageValidationOut {
  valid: boolean;
  family_id: string | null;
  manifest_path: string | null;
  ped_path: string | null;
  sample_ids: string[];
  errors: FamilyImportValidationIssue[];
  warnings: FamilyImportValidationIssue[];
  datasets: FamilyImportDatasetSummary[];
  metadata: Record<string, unknown>;
}

export interface FamilyParaphaseTableOut {
  samples: FamilyMemberOut[];
  genes: ParaphaseGeneResultOut[];
  genes_count: number;
}

export interface FamilyPhenotypeMatchOut {
  group: string;
  sample_id: string | null;
  query_hpo_ids: string[];
  results: PhenotypeMatchResultOut[];
  source: string;
}

/**
 * Short-lived URL for a sample's rendered sequencing-QC report.
 *
 * The report is untrusted pipeline HTML, so it is opened in a new tab against an
 * isolated response rather than embedded in the application.
 */
export interface FamilyQcReportLinkOut {
  url: string;
  expires_at: string;
  filename: string;
}

export interface FamilyRawFilesOut {
  family_id: string;
  family_files: RawImportFileOut[];
  individual_files: RawImportFileOut[];
}

export interface FamilyRegionOfInterestOut {
  query: string;
  label: string;
  source: "gene" | "region";
  assembly_id: string | null;
  chr: string;
  start: number;
  end: number;
}

export interface FamilyRegionOfInterestUpdate {
  query?: string | null;
  project_id?: string | null;
}

/**
 * Canonical family graph edge between two members.
 *
 * ``relative`` links a member to the family through another member (``sample_id_a``),
 * by a degree that is not known: a PGT index known to be on the mother's side, say.
 */
export interface FamilyRelationshipOut {
  id: string;
  relationship_type: "parent_child" | "couple" | "relative";
  sample_id_a: string;
  sample_id_b: string;
  role_a: string | null;
  role_b: string | null;
  source: string;
  metadata: Record<string, unknown>;
}

export interface FamilyRepeatExpansionTableOut {
  samples: FamilyMemberOut[];
  loci: RepeatExpansionRowOut[];
  loci_count: number;
}

export interface FamilyStatusCreate {
  label: string;
  description?: string | null;
  color?: string | null;
  sort_order?: number | null;
}

/** An admin-managed family status value. */
export interface FamilyStatusOut {
  id: string;
  key: string;
  label: string;
  description: string | null;
  color: string;
  sort_order: number;
  is_active: boolean;
}

/** Compact status reference embedded in a family record. */
export interface FamilyStatusRef {
  key: string;
  label: string;
  color: string;
}

export interface FamilyStatusUpdate {
  label?: string | null;
  description?: string | null;
  color?: string | null;
  sort_order?: number | null;
  is_active?: boolean | null;
}

export interface FamilyStructureCoupleUpdate {
  partners: string[];
  context?: string | null;
  metadata?: Record<string, unknown>;
}

export interface FamilyStructureMemberCreate {
  sample_id: string;
  sex?: "male" | "female" | "und";
  role?: "proband" | "father" | "mother" | "sibling" | "embryo" | "relative";
  clinical_status?: "unknown" | "unaffected" | "affected";
  carrier_status?: "unknown" | "not_carrier" | "carrier";
  carrier_type?: "obligate" | "proven" | "reported" | "inferred" | null;
  carrier_evidence?: Record<string, unknown>;
}

export interface FamilyStructureMemberUpdate {
  sample_id: string;
  sex?: "male" | "female" | "und" | null;
  role?: "proband" | "father" | "mother" | "sibling" | "embryo" | "relative" | null;
  clinical_status?: "unknown" | "unaffected" | "affected" | null;
  carrier_status?: "unknown" | "not_carrier" | "carrier" | null;
  carrier_type?: "obligate" | "proven" | "reported" | "inferred" | null;
  carrier_evidence?: Record<string, unknown> | null;
  active?: boolean | null;
}

export interface FamilyStructureParentChildUpdate {
  parent: string;
  child: string;
  parent_role?: "father" | "mother" | "parent";
  metadata?: Record<string, unknown>;
}

export interface FamilyStructureRelationshipsUpdate {
  parent_child?: FamilyStructureParentChildUpdate[];
  couples?: FamilyStructureCoupleUpdate[];
  relatives?: FamilyStructureRelativeUpdate[] | null;
}

/** A member related to the family through another member, by an unknown degree. */
export interface FamilyStructureRelativeUpdate {
  member: string;
  related_to: string;
  metadata?: Record<string, unknown>;
}

export interface FamilyStructureUpdate {
  expected_structure_version?: number | null;
  change_reason?: string | null;
  clear_existing_genomic_data?: boolean;
  add_members?: FamilyStructureMemberCreate[];
  members?: FamilyStructureMemberUpdate[];
  remove_members?: string[];
  relationships?: FamilyStructureRelationshipsUpdate | null;
}

export interface FamilyStructureUpdateOut {
  family: FamilyOut;
  warnings: string[];
  stale_analysis_scopes: string[];
  data_counts: Record<string, number>;
  cleared_data_counts: Record<string, number>;
}

export interface FamilyStructureVersionOut {
  version: number;
  structure_hash: string | null;
  metadata: Record<string, unknown>;
}

export interface FamilyTrackAvailabilityOut {
  samples: Record<string, TrackAvailabilityOut>;
}

export interface GeneAssemblyLocationOut {
  assembly_id: string;
  assembly_name: string;
  assembly_version: string | null;
  chr: string;
  start: number;
  end: number;
  transcript_count: number;
  is_primary: boolean;
  is_family_context: boolean;
}

export interface GeneExonOut {
  start: number;
  end: number;
  name: string;
}

export interface GeneExternalLinkOut {
  label: string;
  href: string;
}

export interface GeneHomologOut {
  species_name: string;
  common_name: string | null;
  symbol: string | null;
  ensembl_gene_id: string | null;
  homology_type: string | null;
  percent_id: number | null;
  percent_coverage: number | null;
  in_platform: boolean;
}

export interface GeneInfoRefreshJobOut {
  _id: string;
  scope: "symbol" | "all_human";
  symbol: string | null;
  status: "queued" | "running" | "completed" | "failed";
  active_slot: string | null;
  worker_id: string | null;
  requested_by: string;
  requested_at: string;
  started_at: string | null;
  heartbeat_at: string | null;
  completed_at: string | null;
  total_symbols: number;
  completed_symbols: number;
  updated_records: number;
  human_assemblies: number;
  current_symbol: string | null;
  error: string | null;
  metadata: Record<string, unknown>;
}

export interface GeneInfoSourceStatusOut {
  status: "success" | "missing" | "not_consulted" | "error";
  fetched_at: string;
  source_url: string | null;
  message: string | null;
  release: string | null;
  release_detail: Record<string, unknown>;
  payload: Record<string, unknown>;
}

export interface GeneInfoSourceSummaryOut {
  source: string;
  latest_fetched_at: string | null;
  success_count: number;
  missing_count: number;
  not_consulted_count: number;
  error_count: number;
  record_count: number;
  release: string | null;
  release_count: number;
}

export interface GeneLocation {
  gene: string;
  chr: string;
  start: number;
  end: number;
  assembly_id: string | null;
  assembly: string | null;
}

export interface GeneMonarchAssociationOut {
  mondo_id: string;
  disease_label: string | null;
  predicate: string;
  predicates: string[];
  sources: string[];
  causal: boolean;
  monarch_url: string | null;
  phenotype_count: number;
  matched_phenotypes: MonarchPhenotypeMatchOut[];
}

export interface GeneOut {
  _id: string;
  gene_id: string;
  hgnc_symbol: string;
  chr: string;
  start: number;
  end: number;
  exons: GeneExonOut[];
  strand: number;
}

export interface GenePanelCreate {
  name: string;
  genes?: string[];
  description?: string | null;
}

export interface GenePanelCreateResponse {
  panel: GenePanelOut;
  message: string;
  missing_genes: string[];
}

export interface GenePanelMembershipOut {
  panel_id: string;
  name: string;
  gene_count: number;
}

export interface GenePanelOut {
  _id: string;
  name: string;
  version: number;
  genes: string[];
  gene_count: number;
  regions: GeneLocation[];
  created_by: string;
  created_by_email: string | null;
  created_at: string;
  description: string | null;
  source: string;
  external_id: string | null;
  external_version: string | null;
  external_url: string | null;
  source_updated_at: string | null;
  source_metadata: Record<string, unknown>;
}

/** Edit a manually-curated panel's genes (the full desired set) → a new version. */
export interface GenePanelUpdate {
  genes?: string[];
  description?: string | null;
}

export interface GenePanelVersionDetail {
  version: number;
  name: string;
  source: string | null;
  external_version: string | null;
  gene_count: number;
  created_by_email: string | null;
  created_at: string;
  description: string | null;
  genes: string[];
  regions: GeneLocation[];
  source_metadata: Record<string, unknown>;
}

export interface GenePanelVersionListOut {
  panel_id: string;
  current_version: number;
  versions: GenePanelVersionSummary[];
}

export interface GenePanelVersionSummary {
  version: number;
  name: string;
  source: string | null;
  external_version: string | null;
  gene_count: number;
  created_by_email: string | null;
  created_at: string;
}

export interface GeneProfileOut {
  assembly_id: string;
  assembly_name: string;
  assembly_version: string | null;
  gene_annotation_source: string | null;
  gene_annotation_imported_at: string | null;
  species_name: string;
  symbol: string;
  gene_id: string;
  display_name: string | null;
  summary: string | null;
  chr: string;
  start: number;
  end: number;
  strand: number;
  biotype: string | null;
  transcript_count: number;
  transcripts: GeneTranscriptOut[];
  aliases: string[];
  previous_symbols: string[];
  ensembl_gene_id: string | null;
  ncbi_gene_id: string | null;
  hgnc_id: string | null;
  omim_gene_id: string | null;
  gene_type: string | null;
  location: string | null;
  assembly_locations: GeneAssemblyLocationOut[];
  homologs: GeneHomologOut[];
  panels: GenePanelMembershipOut[];
  family_counts: GeneVariantCountsOut | null;
  source_status: Record<string, GeneInfoSourceStatusOut>;
  external_links: GeneExternalLinkOut[];
  monarch_associations: GeneMonarchAssociationOut[];
  extra: Record<string, unknown>;
  updated_at: string | null;
}

export interface GeneReferenceAdminStatusOut {
  active_job: GeneInfoRefreshJobOut | null;
  recent_jobs: GeneInfoRefreshJobOut[];
  source_summaries: GeneInfoSourceSummaryOut[];
  total_cached_records: number;
  human_gene_symbols: number;
  human_assemblies: number;
  last_completed_at: string | null;
}

export interface GeneSearchResultOut {
  symbol: string;
  gene_id: string;
  chr: string;
  start: number;
  end: number;
  transcript_count: number;
  assembly_count: number;
}

export interface GeneTranscriptOut {
  transcript_id: string;
  start: number;
  end: number;
  exon_count: number;
  strand: number;
  biotype: string | null;
  source: string | null;
  mane_select: boolean;
  mane_plus_clinical: boolean;
  ensembl_canonical: boolean;
  ccds_id: string | null;
  refseq_accessions: string[];
}

export interface GeneVariantCountsOut {
  small_variants: number;
  structural_variants: number;
}

export interface GenotypeOut {
  sample: string;
  gt: string;
  dp: number | null;
  ad: number[] | null;
  af: number[] | null;
  read_support: number | null;
  qual: number | null;
  filter: string | null;
  ps: number | null;
  gq: number | null;
  cn: number | null;
}

export interface GithubReleaseCatalogOut {
  repository: string;
  repository_url: string;
  releases_url: string;
  issues_url: string;
  repo_visibility: "private" | "public" | "unknown";
  sync_status: "ok" | "unavailable";
  sync_error: string | null;
  fetched_at: string | null;
  releases: GithubReleaseOut[];
}

export interface GithubReleaseOut {
  version: string;
  name: string | null;
  published_at: string;
  summary: string;
  url: string;
  prerelease: boolean;
}

export interface GlobalVariantPageOut {
  total: number;
  total_is_estimated: boolean;
  page_size: number;
  next_cursor: string | null;
  assembly_id: string | null;
  assembly_name: string | null;
  variants: GlobalVariantRowOut[];
}

/**
 * One unique variant aggregated across every project the user can access.
 *
 * ``key`` is the ClickHouse UInt64 variant key serialised as a string to avoid
 * JavaScript precision loss on the frontend.
 */
export interface GlobalVariantRowOut {
  key: string;
  variant_id: string;
  chr: string;
  pos: number;
  ref: string | null;
  alt: string | null;
  rsid: string | null;
  type: string;
  gene: string | null;
  gene_symbols: string[];
  impact: string | null;
  consequence: string | null;
  effects: string[];
  hgvsc: string | null;
  hgvsp: string | null;
  clinvar: string | null;
  classification: string | null;
  tags: string[];
  total_samples: number;
  het_samples: number;
  hom_samples: number;
  total_families: number;
  last_seen: string | null;
}

export interface HTTPValidationError {
  detail: ValidationError[];
}

export interface HaplotypeResponse {
  chr: string;
  start: number | null;
  end: number | null;
  samples: HaplotypeSample[];
}

export interface HaplotypeSample {
  sample: string;
  segments: HaplotypeSegment[];
}

export interface HaplotypeSegment {
  chr: string | null;
  start: number;
  end: number;
  hap1: string;
  hap2: string;
  ps: number | null;
  hap1_lineage: string | null;
  hap2_lineage: string | null;
  hemizygous_in_males: boolean;
}

export interface HpoAdminSummaryOut {
  total_terms: number;
  active_terms: number;
  obsolete_terms: number;
  release_version: string | null;
  release_date: string | null;
  last_sync_date: string | null;
  automatic_update_supported: boolean;
  ontology_loaded: boolean;
  ontology_path: string | null;
}

export interface HpoAdminTermOut {
  hpo_id: string;
  label: string;
  definition: string | null;
  is_obsolete: boolean;
  replaced_by: string | null;
  release_version: string | null;
  release_date: string | null;
  synonyms: string[];
  parents: HpoTermRelationOut[];
  children: HpoTermRelationOut[];
  parent_count: number;
  child_count: number;
}

export interface HpoAnnotationCreate {
  hpo_id: string;
  status?: "present" | "absent" | "unknown";
  onset?: string | null;
  evidence?: string | null;
  source?: string | null;
  note?: string | null;
}

export interface HpoAnnotationOut {
  id: string;
  sample_id: string;
  hpo_id: string;
  label: string;
  definition: string | null;
  status: "present" | "absent" | "unknown";
  onset: string | null;
  evidence: string | null;
  source: string;
  note: string | null;
  created_at: string;
  updated_at: string;
}

export interface HpoAnnotationUpdate {
  hpo_id?: string | null;
  status?: "present" | "absent" | "unknown" | null;
  onset?: string | null;
  evidence?: string | null;
  source?: string | null;
  note?: string | null;
}

export interface HpoFamilyQueryOut {
  hpo_id: string;
  include_descendants: boolean;
  sample_ids: string[];
  annotations: HpoAnnotationOut[];
}

export interface HpoOntologyImportOut {
  terms: number;
  synonyms: number;
  edges: number;
  closure_rows: number;
}

export interface HpoOntologySyncOut {
  preview_only: boolean;
  release_version: string | null;
  release_date: string | null;
  current: HpoAdminSummaryOut;
  preview: Record<string, number>;
  imported: HpoOntologyImportOut | null;
}

export interface HpoOntologySyncRequest {
  path: string;
  release_version?: string | null;
  release_date?: string | null;
  preview_only?: boolean;
}

export interface HpoTermDetailOut {
  hpo_id: string;
  label: string;
  definition: string | null;
  is_obsolete: boolean;
  replaced_by: string | null;
  release_version: string | null;
  release_date: string | null;
  synonyms: string[];
  parents: HpoTermRelationOut[];
  children: HpoTermRelationOut[];
}

export interface HpoTermOut {
  hpo_id: string;
  label: string;
  definition: string | null;
  is_obsolete: boolean;
}

export interface HpoTermRelationOut {
  hpo_id: string;
  label: string;
  relation: string;
}

export interface IdeogramBandOut {
  name: string;
  start: number;
  end: number;
  stain: string;
}

/** A signed chain-head anchor (the verbatim signed blob is self-verifying). */
export interface IntegrityAnchorOut {
  anchor_seq: number;
  created_at: string;
  prev_anchor_hash: string | null;
  anchor_root: string;
  anchor_hash: string;
  chain_count: number;
  key_id: string;
  algo: string;
  public_key: string | null;
  signature: string | null;
}

/** Result of verifying the live chains against the latest signed anchor. */
export interface IntegrityAnchorVerifyOut {
  status: string;
  anchor_seq: number | null;
  chain_count: number;
  diverged: Record<string, unknown>[];
  reason: string | null;
}

/** Result of re-walking an append-only table's per-family tamper-evidence chain. */
export interface IntegrityVerifyOut {
  table: string;
  family_id: string;
  verified: boolean;
  rows_checked: number;
  first_bad_row: string | null;
  reason: string | null;
}

export interface ManualPedCoupleCreate {
  partners: string[];
  context?: string | null;
  metadata?: Record<string, unknown>;
}

export interface ManualPedFamilyCreate {
  family_id: string;
  members: ManualPedMemberCreate[];
  couples?: ManualPedCoupleCreate[];
  project_id?: string | null;
  metadata?: Record<string, unknown>;
}

export interface ManualPedMemberCreate {
  sample_id: string;
  father_id?: string | null;
  mother_id?: string | null;
  sex?: "male" | "female" | "und";
  clinical_status?: "unknown" | "unaffected" | "affected";
  affected?: boolean;
  is_proband?: boolean;
  carrier_status?: "unknown" | "not_carrier" | "carrier";
  carrier_type?: "obligate" | "proven" | "reported" | "inferred" | null;
  carrier_evidence?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
}

export interface MendeliomeRegenerateResponse {
  panel: GenePanelOut;
  message: string;
  changed: boolean;
  version: number;
  monarch_release: string | null;
  gene_count: number;
  missing_genes: string[];
}

export interface MitoDNACoverageOut {
  mean_depth: number | null;
  min_depth: number | null;
  max_depth: number | null;
  breadth: number | null;
  source: string | null;
  regions: number;
}

export interface MitoDNAQcOut {
  status: "pass" | "warn" | "fail" | "skip";
  notes: string[];
  contamination: number | null;
  mean_depth: number | null;
  min_mean_depth: number | null;
}

export interface MitoDNASampleOut {
  sample_id: string;
  role: string | null;
  affected: boolean | null;
  sex: string | null;
  haplogroup: string | null;
  coverage: MitoDNACoverageOut;
  qc: MitoDNAQcOut;
}

export interface MitoDNAStructuralVariantCallOut {
  sample: string;
  role: string | null;
  genotype: string;
  heteroplasmy: number | null;
  read_support: number | null;
}

export interface MitoDNAStructuralVariantOut {
  variant_id: string;
  sv_type: string;
  start: number;
  end: number;
  length: number | null;
  genes: string[];
  source: string | null;
  filters: string[];
  calls: Record<string, MitoDNAStructuralVariantCallOut>;
}

export interface MitoDNAVariantAnnotationOut {
  region: string;
  gene: string | null;
  consequence: string | null;
  consequence_terms: string[];
  gnomad_af: number | null;
  category: string | null;
  clinical_significance: "pathogenic" | "likely_pathogenic" | "benign" | "likely_benign" | "reported" | "uncertain" | "polymorphism" | "unknown";
  disorders: string[];
  polymorphism_notes: string[];
  mitomap_query: string;
  mitomap_url: string;
  source_keys: string[];
}

export interface MitoDNAVariantOut {
  variant_id: string;
  position: number;
  ref: string;
  alt: string;
  label: string;
  type: string;
  rsid: string | null;
  annotation: MitoDNAVariantAnnotationOut;
  calls: Record<string, MitoDNAVariantSampleCallOut>;
  maternal_transmission: "maternal_shared" | "maternal_not_observed" | "maternal_only" | "father_only" | "family_private" | "no_alt_calls" | "unknown";
  review: SmallVariantReviewOut | null;
}

export interface MitoDNAVariantSampleCallOut {
  sample: string;
  role: string | null;
  affected: boolean | null;
  sex: string | null;
  genotype: string;
  allele_fraction: number | null;
  depth: number | null;
  alt_depth: number | null;
  zygosity: "homoplasmic" | "heteroplasmic" | "low_level" | "reference" | "no_call" | "unknown";
  display: string;
}

export interface MonarchGeneOverviewItemOut {
  gene_symbol: string;
  hgnc_id: string;
  causal: boolean;
  disease_count: number;
}

export interface MonarchGeneOverviewOut {
  total: number;
  genes: MonarchGeneOverviewItemOut[];
}

export interface MonarchPhenotypeMatchOut {
  hpo_id: string;
  label: string | null;
}

export interface MonarchRefreshSummaryOut {
  release_version: string | null;
  mendeliome_regenerated: boolean;
  mendeliome_error: string | null;
  files_loaded: number;
  gene_disease_pairs: number;
  genes: number;
  diseases: number;
  causal_pairs: number;
  disease_phenotype_pairs: number;
  phenotype_diseases: number;
  phenotypes: number;
  excluded_phenotype_pairs: number;
  completed_at: string;
  duration_seconds: number;
}

export interface MonarchSearchDiseaseOut {
  mondo_id: string;
  disease_label: string | null;
  match_type: "disease" | "phenotype" | "both";
  gene_count: number;
  genes: MonarchSearchGeneOut[];
  phenotype_count: number;
  matched_phenotype_count: number;
  phenotypes: MonarchSearchPhenotypeOut[];
}

export interface MonarchSearchGeneOut {
  gene_symbol: string;
  hgnc_id: string;
  predicate: string | null;
  causal: boolean;
}

export interface MonarchSearchOut {
  query: string;
  total: number;
  diseases: MonarchSearchDiseaseOut[];
  gene_overview: MonarchGeneOverviewOut;
}

export interface MonarchSearchPhenotypeOut {
  hpo_id: string;
  phenotype_label: string | null;
  matched: boolean;
}

export interface MonarchStatusOut {
  release_version: string | null;
  gene_disease_pairs: number;
  genes: number;
  diseases: number;
  causal_pairs: number;
  disease_phenotype_pairs: number;
  phenotype_diseases: number;
  phenotypes: number;
  last_updated_at: string | null;
}

/** Seed the artifact list from internal cohort recurrence. */
export interface NiptArtifactAutoSeed {
  assembly_id: string;
  assay_key?: string;
  min_carrier_samples?: number;
}

export interface NiptArtifactAutoSeedOut {
  seeded: number;
  min_carrier_samples: number;
}

/** Create/update a NIPT artifact within an assembly + assay/panel scope. */
export interface NiptArtifactCreate {
  assembly_id: string;
  variant_id: string;
  assay_key?: string;
  label?: string | null;
  source?: "curated" | "auto";
  recurrence_count?: number;
}

/**
 * What an artefact-table import did: the rows it read, those the table does not flag
 * as artefacts or could not read, the alleles it added, and those it refused because
 * their annotation is common or may assert pathogenic in ClinVar.
 */
export interface NiptArtifactImportOut {
  rows_read: number;
  not_flagged: number;
  invalid: number;
  imported: number;
  protected_common: number;
  protected_clinvar: number;
}

/** A recurrent-artifact (panel-of-normals) entry for monogenic NIPT. */
export interface NiptArtifactOut {
  id: string;
  assembly_id: string;
  assay_key: string;
  variant_id: string;
  recurrence_count: number;
  source: string;
  label: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * The NIPT classification block attached to each cfDNA variant.
 *
 * The variant payload itself is the full small-variant shape (``VariantOut``);
 * this is the maternal/fetal interpretation layered on top. ``NiptVariantOut``
 * (defined after ``VariantOut`` below) combines the two.
 */
export interface NiptClassificationOut {
  category: number | null;
  category_label: string;
  maternal_state: string;
  fetal_inheritance: string;
  expected_vaf: number;
  observed_vaf: number | null;
  confidence: number;
  flags: string[];
  runner_up_category: number | null;
  runner_up_confidence: number | null;
  paternal_transmission_probability: number | null;
  maternal_allele_probability: number | null;
  fetal_hom_alt_probability: number | null;
  fetal_genotype_posterior: Record<string, number> | null;
  quality_failures: string[];
  cf_alt_reads: number | null;
  cf_depth: number | null;
  cf_depth_estimated: boolean;
  father_state: string | null;
  father_vaf: number | null;
  father_depth: number | null;
  de_novo: NiptDeNovoTriageOut | null;
}

/** A panel gene / target region flagged as inadequately interrogated. */
export interface NiptCoverageLowRegionOut {
  label: string;
  chr: string;
  median_coverage: number | null;
  covered_fraction: number;
  reason: string;
}

/** On-target coverage for a single target region. */
export interface NiptCoverageRegionOut {
  label: string;
  chr: string;
  start: number;
  end: number;
  median_coverage: number | null;
  covered_bases: number;
  target_bases: number;
}

/**
 * Median on-target coverage for a monogenic NIPT family's cfDNA sample.
 *
 * ``low_coverage_regions`` is a compact QC list (only the failing genes, not
 * the full per-region table) flagging genes that may harbour silent gaps.
 */
export interface NiptCoverageSummaryOut {
  family_id: string;
  overall_median_on_target: number | null;
  target_region_count: number;
  per_region: NiptCoverageRegionOut[];
  min_depth: number;
  min_covered_fraction: number;
  low_coverage_regions: NiptCoverageLowRegionOut[];
  targets: NiptTargetCoverageOut | null;
}

/**
 * A de novo candidate's triage (the R NIPT-M rules): where its allele fraction falls
 * in the fetal window, its score and priority, and what lowered or raised it.
 */
export interface NiptDeNovoTriageOut {
  window: "strict" | "loose" | "below" | "above";
  score: number;
  label: "high" | "medium" | "low" | "excluded_recurrent" | "outside_window";
  reasons: string[];
  other_cfdna_carriers: number;
}

/** The family's fetal window the de novo triage reads (allele fractions). */
export interface NiptDeNovoWindowOut {
  strict_min: number;
  strict_max: number;
  loose_min: number;
  loose_max: number;
}

/** Fetal-fraction estimate for a monogenic NIPT family. */
export interface NiptFetalFractionOut {
  ff: number;
  ff_computed: number | null;
  ff_median: number | null;
  ci_low: number | null;
  ci_high: number | null;
  n_sites: number;
  method: string;
  low_confidence: boolean;
  vaf_q05: number | null;
  vaf_q95: number | null;
}

/** The fetal sex from the father's X alleles in the plasma and from its chrY coverage. */
export interface NiptFetalSexOut {
  call: "female" | "male" | "indeterminate" | "discordant";
  paternal_x: string;
  x_transmitted: number;
  x_not_transmitted: number;
  informative_sites: number;
  chry_profile: string | null;
  y_ratio: number | null;
  x_ratio: number | null;
  chry_fetal_fraction: number | null;
}

/**
 * Every capture target of one gene in the plasma's target table, for the coverage page
 * (REQ-NIPT-006); empty without a target table or for a gene the panel does not capture.
 */
export interface NiptGeneTargetsOut {
  family_id: string;
  gene: string;
  critical_mean_depth: number;
  targets: NiptTargetDetailOut[];
}

/**
 * The model the analysis ran with: its validation, the cfDNA quality filter and the
 * paternal genotype classes.
 */
export interface NiptModelOut {
  reference: string;
  overdispersion: number;
  maternal_het_bias: number;
  min_quality: number;
  min_alt_reads: number;
  min_vaf: number;
  vaf_ff_fraction: number;
  max_strand_bias_fs: number;
  father_het_min_vaf: number;
  father_hom_alt_min_vaf: number;
  min_father_depth: number;
}

/**
 * Whether the fetus inherited the father's alleles: at the autosomal sites where he
 * carries one and the mother does not, with enough plasma depth to see it. The fetus
 * inherits every allele he is homozygous for and half of his het ones.
 */
export interface NiptPaternityOut {
  hom_alt_transmitted: number;
  hom_alt_not_transmitted: number;
  het_transmitted: number;
  het_not_transmitted: number;
  hom_alt_rate: number | null;
  het_rate: number | null;
  status: "pass" | "warn" | "fail";
  message: string;
}

/**
 * The NIPT quality checks: the de novo window, paternity, fetal sex, the plasma's sex
 * profile and target coverage, and why cfDNA calls failed the quality filter.
 */
export interface NiptQcOut {
  de_novo_window: NiptDeNovoWindowOut | null;
  paternity: NiptPaternityOut;
  fetal_sex: NiptFetalSexOut;
  plasma_profile_status: "pass" | "warn" | "fail" | "unknown";
  plasma_profile_message: string;
  target_coverage: NiptTargetCoverageOut | null;
  quality_failures: Record<string, number>;
  model: NiptModelOut;
}

export interface NiptRecessiveAlleleOut {
  variant_id: string;
  inherited_probability: number | null;
  category: number | null;
  note: string | null;
}

/**
 * A gene where both parents carry an allele: whether the fetus inherited each, and
 * the probability it inherited one of each (a carrier couple's prior is 25%).
 */
export interface NiptRecessiveGeneOut {
  gene: string;
  maternal: NiptRecessiveAlleleOut[];
  paternal: NiptRecessiveAlleleOut[];
  risk: number | null;
  maternal_variant_id: string | null;
  paternal_variant_id: string | null;
  risk_uses_prior: boolean;
}

/** Monogenic NIPT analysis summary: fetal fraction and category/filter counts. */
export interface NiptSummaryOut {
  family_id: string;
  fetal_fraction: NiptFetalFractionOut;
  category_counts: Record<string, number>;
  filter_counts: Record<string, number>;
  qc: NiptQcOut | null;
}

export interface NiptTargetCoverageGeneOut {
  gene: string;
  targets: number;
  weak_targets: number;
  min_mean: number | null;
  mean_of_means: number | null;
  weak: NiptTargetOut[];
}

/**
 * The plasma's per-target coverage QC: every target, or a panel's or genes'. A target
 * is weak when its mean depth is below ``critical_mean_depth`` or a base has no coverage.
 */
export interface NiptTargetCoverageOut {
  targets: number;
  median_mean: number | null;
  q05_mean: number | null;
  below_critical: number;
  below_advisory: number;
  zero_mean: number;
  incomplete: number;
  critical_mean_depth: number;
  advisory_mean_depth: number;
  genes: NiptTargetCoverageGeneOut[];
}

/**
 * A target and whether it is weak: a mean below the critical depth, or a base without
 * coverage (``TargetCoverageRow.is_weak``).
 */
export interface NiptTargetDetailOut {
  chr: string;
  start: number;
  end: number;
  gene: string;
  attribute: string;
  mean: number | null;
  median: number | null;
  min: number | null;
  proportion_covered: number | null;
  weak: boolean;
}

/** A capture target (an exon of a panel transcript) and its depth. */
export interface NiptTargetOut {
  chr: string;
  start: number;
  end: number;
  gene: string;
  attribute: string;
  mean: number | null;
  median: number | null;
  min: number | null;
  proportion_covered: number | null;
}

/**
 * A classified cfDNA variant: the full small-variant payload plus the NIPT
 * classification block. Defined here so it can extend ``VariantOut`` (declared
 * earlier in this module); ``NiptVariantPage`` forward-references it.
 */
export interface NiptVariantOut {
  _id: string;
  chr: string;
  start: number;
  end: number;
  length: number;
  type: string;
  source: string | null;
  qual: number | null;
  read_support: number | null;
  filter: string | null;
  remote_chr: string | null;
  remote_start: number | null;
  ref: string | null;
  alt: string | null;
  ps: number | null;
  gene: string | null;
  gene_id: string | null;
  gene_symbols: string[];
  gene_count: number | null;
  transcript_id: string | null;
  feature_type: string | null;
  transcript_biotype: string | null;
  impact: string | null;
  effect: string | null;
  clinvar: string | null;
  rsid: string | null;
  hgvsc: string | null;
  hgvsp: string | null;
  canonical: boolean;
  mane_select: boolean;
  mane_plus_clinical: boolean;
  exon: string | null;
  intron: string | null;
  lof: string | null;
  lof_filter: string | null;
  lof_flags: string | null;
  gnomad_af: number | null;
  gnomad_hom_count: number | null;
  gene_pli: number | null;
  gene_missense_z: number | null;
  population_frequencies: Record<string, number>;
  cadd_raw: number | null;
  cadd_phred: number | null;
  revel: number | null;
  sift: string | null;
  polyphen: string | null;
  spliceai_ds_ag: number | null;
  spliceai_ds_al: number | null;
  spliceai_ds_dg: number | null;
  spliceai_ds_dl: number | null;
  spliceai_max: number | null;
  alpha_missense_pathogenicity: number | null;
  alpha_missense_class: string | null;
  cytoband: string | null;
  annotation_extra: Record<string, unknown>;
  transcripts: SmallVariantTranscriptOut[];
  genotypes: GenotypeOut[];
  hemizygous_in_males: boolean;
  review: SmallVariantReviewOut | null;
  internal_cohort: VariantInternalCohortOut | null;
  priority: VariantPriorityOut | null;
  sv_second_hit: SvSecondHitOut | null;
  nipt: NiptClassificationOut;
}

/** A page of classified cfDNA variants plus the family's fetal fraction. */
export interface NiptVariantPage {
  family_id: string;
  total: number;
  total_is_estimated: boolean;
  count_limit: number | null;
  fetal_fraction: NiptFetalFractionOut;
  variants: NiptVariantOut[];
  recessive_genes: NiptRecessiveGeneOut[];
}

export interface PanelAppImportRequest {
  panelapp_id: number;
  version?: string | null;
  confidence_levels?: ("1" | "2" | "3")[];
  include_regions?: boolean;
  include_strs?: boolean;
  assembly?: "GRCh38" | "GRCh37";
  name?: string | null;
}

export interface PanelAppImportResponse {
  panel: GenePanelOut;
  message: string;
  missing_genes: string[];
  imported_gene_count: number;
  imported_region_count: number;
}

export interface PanelAppPanelSearchResponse {
  results: PanelAppPanelSummaryOut[];
  count: number;
}

export interface PanelAppPanelSummaryOut {
  panelapp_id: number;
  name: string;
  disease_group: string | null;
  disease_sub_group: string | null;
  status: string | null;
  version: string | null;
  version_created: string | null;
  relevant_disorders: string[];
  gene_count: number;
  str_count: number;
  region_count: number;
  types: string[];
  url: string;
}

export interface ParaphaseClinicalOut {
  interpretation: string | null;
  normal: string | null;
  carrier: string | null;
  pathogenic: string | null;
  caveats: string | null;
}

export interface ParaphaseDisorderOut {
  name: string;
  omim_url: string | null;
}

export interface ParaphaseExtraFieldOut {
  key: string;
  label: string;
  value: unknown;
  description: string | null;
}

export interface ParaphaseGeneResultOut {
  gene_symbol: string;
  is_medically_relevant: boolean;
  region_info: ParaphaseRegionInfoOut | null;
  max_total_cn: number | null;
  max_gene_cn: number | null;
  max_highest_total_cn: number | null;
  has_copy_number_signal: boolean;
  samples: Record<string, ParaphaseSampleResultOut>;
}

export interface ParaphaseHaplotypeGroupOut {
  key: string;
  label: string;
  count: number;
  haplotypes: string[];
}

export interface ParaphaseMetricOut {
  key: string;
  label: string;
  value: number | null;
}

export interface ParaphaseRegionInfoOut {
  region_id: string;
  display_name: string;
  genes: string[];
  summary: string | null;
  clinical: ParaphaseClinicalOut | null;
  clinical_priority: number;
  key_copy_number_fields: string[];
  key_read_fields: string[];
  key_haplotype_fields: string[];
  key_extra_fields: string[];
  field_descriptions: Record<string, string>;
  notes: string[];
  disorders: ParaphaseDisorderOut[];
}

export interface ParaphaseSampleResultOut {
  sample: string;
  role: string | null;
  affected: boolean | null;
  sex: string | null;
  clinical_status: string | null;
  total_cn: number | null;
  gene_cn: number | null;
  highest_total_cn: number | null;
  sample_sex: string | null;
  phase_region: string | null;
  region_depth: Record<string, unknown>;
  genome_depth: number | null;
  final_haplotype_count: number;
  assembled_haplotype_count: number;
  variant_site_count: number;
  heterozygous_site_count: number;
  fusion_count: number | null;
  copy_number_signal: boolean;
  copy_number_metrics: ParaphaseMetricOut[];
  read_metrics: ParaphaseMetricOut[];
  haplotype_groups: ParaphaseHaplotypeGroupOut[];
  extra_fields: ParaphaseExtraFieldOut[];
  uploaded_at: string | null;
}

export interface PedFamilyResult {
  family_id: string;
  samples: string[];
}

export interface PedUploadResult {
  families: PedFamilyResult[];
}

/**
 * One informative imputed marker (raw call), with the value drawn on each
 * haplotype lane (0/1, null = uninformative):
 *
 * - For a child: ``hap1`` = the paternal homolog inherited, ``hap2`` = the
 *   maternal homolog inherited, oriented to match the stored haplotype blocks.
 * - For a parent: ``hap1`` / ``hap2`` are the alleles on their own two phased
 *   homologs (the raw per-site version of their haplotype blocks).
 *
 * The father's and mother's genotype at a site (shown in the tooltip) are
 * reconstructed client-side from the father/mother marker rows at that position,
 * so they are not duplicated onto every marker.
 */
export interface PhasedMarker {
  pos: number;
  hap1: number | null;
  hap2: number | null;
}

export interface PhasedMarkerResponse {
  chr: string;
  start: number | null;
  end: number | null;
  samples: PhasedMarkerSample[];
  sites: PhasedSite[];
  truncated: boolean;
  covered: number[] | null;
}

export interface PhasedMarkerSample {
  sample: string;
  markers: PhasedMarker[];
  reference: boolean;
  qc: PhasedSampleQc | null;
}

/**
 * Per-child phasing QC summary for one region.
 *
 * Computed only for the index couple's own children (the members for whom
 * parent-of-origin is defined). ``informative_sites`` counts sites where both
 * parents and the child carry a valid phased genotype (the joint-informative
 * denominator). ``mendel_errors`` counts the subset of those sites whose child
 * genotype is impossible given the parents' alleles — a true Mendelian
 * inconsistency (likely sample swap / wrong pedigree), NOT mere parent-of-origin
 * ambiguity. ``mendel_rate`` = mendel_errors / informative_sites (0 when none).
 */
export interface PhasedSampleQc {
  informative_sites: number;
  mendel_errors: number;
  mendel_rate: number;
}

/**
 * Raw phased genotypes at one imputed site, for the marker hover tooltip.
 *
 * ``gts`` is aligned to the response's ``samples`` order; each entry is that
 * member's phased ``a|b`` genotype (allele indices as a string), decoded to
 * nucleotides client-side via ``ref``/``alt``.
 */
export interface PhasedSite {
  pos: number;
  ref: string;
  alt: string;
  gts: string[];
}

export interface PhenotypeMatchResultOut {
  rank: number;
  score: number | null;
  id: string;
  name: string;
  category: string | null;
  symbol: string | null;
  gene_in_platform: boolean;
  matching_phenotypes: PhenotypeTermRefOut[];
  extra_phenotypes: PhenotypeTermRefOut[];
}

export interface PhenotypeTermRefOut {
  hpo_id: string;
  label: string | null;
}

export interface ProjectCreate {
  name: string;
  description?: string | null;
  species_id: string;
  assembly_id: string;
  user_ids?: string[];
}

export interface ProjectDashboardOut {
  _id: string;
  name: string;
  description: string | null;
  species_id: string;
  assembly_id: string;
  user_ids: string[];
  metadata: Record<string, unknown>;
  species_name: string | null;
  assembly_name: string | null;
  assembly_version: string | null;
  assembly_validated: boolean;
  families: FamilyOut[];
  samples: string[];
}

export interface ProjectOut {
  _id: string;
  name: string;
  description: string | null;
  species_id: string;
  assembly_id: string;
  user_ids: string[];
  metadata: Record<string, unknown>;
}

export interface ProjectUpdate {
  name?: string | null;
  description?: string | null;
  species_id?: string | null;
  assembly_id?: string | null;
  user_ids?: string[] | null;
}

export interface ProjectsUpdate {
  project_ids?: string[];
}

/**
 * A sequencing-QC metric a threshold can be set on.
 *
 * The catalogue is fixed in code (it follows what the QC parsers emit), so the admin
 * UI reads it rather than letting an operator invent metric keys or invert a
 * comparison direction.
 */
export interface QcMetricCatalogueOut {
  key: string;
  label: string;
  unit: string;
  direction: "lower_is_worse" | "higher_is_worse";
  help_text: string;
}

export interface QcThresholdCatalogueOut {
  metrics: QcMetricCatalogueOut[];
  profiles: QcThresholdProfileOut[];
  changes: QcThresholdChangeOut[];
}

/** One entry of the append-only cut-off history, with both sides of the edit. */
export interface QcThresholdChangeOut {
  profile_key: string;
  metric_key: string;
  previous_warn_value: number | null;
  previous_error_value: number | null;
  warn_value: number | null;
  error_value: number | null;
  changed_by_email: string | null;
  changed_at: string;
  reason: string | null;
}

export interface QcThresholdOut {
  metric_key: string;
  label: string;
  unit: string;
  direction: "lower_is_worse" | "higher_is_worse";
  known_metric: boolean;
  warn_value: number | null;
  error_value: number | null;
}

/**
 * A new, empty QC threshold profile.
 *
 * No cut-offs are copied from anywhere: a profile exists because an assay is judged
 * differently, so an inherited number would carry an authority nobody granted it.
 */
export interface QcThresholdProfileCreate {
  label: string;
  key?: string | null;
  description?: string | null;
}

/** A named set of sequencing-QC cut-offs (one per assay type). */
export interface QcThresholdProfileOut {
  id: string;
  key: string;
  label: string;
  description: string | null;
  is_default: boolean;
  sort_order: number;
  thresholds: QcThresholdOut[];
}

/**
 * Set or clear one metric's cut-offs in a profile.
 *
 * Both bounds null clears the threshold — a metric with no cut-off is not configured.
 */
export interface QcThresholdUpdate {
  reason: string;
  metric_key: string;
  warn_value?: number | null;
  error_value?: number | null;
}

export interface RawImportFileOut {
  id: string;
  scope: string;
  dataset: string;
  file_name: string;
  file_type: string;
  sample_id: string | null;
  storage_path: string;
  file_size: number | null;
  sha256: string | null;
  source: string;
  created_at: string | null;
  exists: boolean | null;
  download_available: boolean;
  in_object_store: boolean;
}

export interface RawImportFileVerifyOut {
  file_id: string;
  status: string;
  expected_sha256: string | null;
  computed_sha256: string | null;
  message: string;
}

export interface ReferenceAutoImportRequest {
  tax_id: number;
  ucsc_genome: string;
  overwrite?: boolean;
}

export interface ReferenceAutoImportResult {
  species_id: string;
  species_name: string;
  assembly_id: string;
  assembly_name: string;
  assembly_version: string;
  ucsc_genome: string;
  created_species: boolean;
  created_assembly: boolean;
  cytobands_inserted: number;
  genes_inserted: number;
  cytobands_replaced: boolean;
  genes_replaced: boolean;
  cytoband_source_url: string;
  gene_source_url: string;
  gene_source: string;
  gene_warning: string | null;
}

export interface ReferenceDatasetImportOut {
  dataset_type: string;
  inserted: number;
  replaced: boolean;
  source: string | null;
  performed_by: string | null;
  performed_at: string;
}

/**
 * One chronological entry for the "Recent reference activity" feed: which
 * dataset was loaded for which assembly, how many rows, from where, by whom.
 */
export interface ReferenceImportActivityOut {
  assembly_id: string;
  assembly_name: string;
  species_name: string;
  dataset_type: string;
  inserted: number;
  replaced: boolean;
  source: string | null;
  performed_by: string | null;
  performed_at: string;
}

export interface ReferenceImportSourceAssemblyOut {
  scientific_name: string;
  common_name: string;
  tax_id: number;
  ucsc_genome: string;
  assembly_name: string;
  assembly_version: string;
  release_date: string | null;
  description: string;
  source_name: string;
  cytobands_available: boolean;
  genes_available: boolean;
  gene_source: string;
}

export interface ReferenceImportSourceOrganismOut {
  scientific_name: string;
  common_name: string;
  tax_id: number;
  assembly_count: number;
}

export interface ReferenceUploadResult {
  assembly_id: string;
  assembly_name: string;
  dataset_type: "cytobands" | "genes" | "blacklist" | "clinical_cnvs" | "segmental_duplications" | "dgv";
  inserted: number;
  replaced: boolean;
}

export interface RepeatExpansionAlleleOut {
  repeat_count: number | null;
  bp_length: number | null;
  confidence_interval: string | null;
  support_reads: number | null;
  purity: number | null;
  methylation: number | null;
  motif_counts: RepeatExpansionMotifCountOut[];
  motif_spans: string | null;
  interrupted: boolean;
  interruption_label: string | null;
  status: "normal" | "review" | "intermediate" | "pathogenic" | "unknown";
}

export interface RepeatExpansionMotifCountOut {
  motif: string;
  count: number;
}

export interface RepeatExpansionRowOut {
  locus_id: string;
  gene: string;
  display_name: string;
  disease: string;
  inheritance: string | null;
  chr: string;
  start: number;
  end: number;
  motif: string | null;
  warning_min: number | null;
  pathogenic_min: number | null;
  benign_min: number | null;
  benign_max: number | null;
  pathogenic_max: number | null;
  status: "normal" | "review" | "intermediate" | "pathogenic" | "unknown";
  calls: Record<string, RepeatExpansionSampleCallOut>;
}

export interface RepeatExpansionSampleCallOut {
  sample: string;
  role: string | null;
  affected: boolean | null;
  sex: string | null;
  genotype: string;
  allele_count: number;
  alleles: RepeatExpansionAlleleOut[];
  status: "normal" | "review" | "intermediate" | "pathogenic" | "unknown";
}

export interface RepeatExpansionTrackItemOut {
  sample: string;
  locus_id: string;
  gene: string;
  display_name: string;
  disease: string;
  chr: string;
  start: number;
  end: number;
  motif: string | null;
  warning_min: number | null;
  pathogenic_min: number | null;
  status: "normal" | "review" | "intermediate" | "pathogenic" | "unknown";
  allele_repeat_counts: number[];
  allele_bp_lengths: number[];
}

export interface RepeatExpansionTrackResponse {
  items: RepeatExpansionTrackItemOut[];
}

export interface RepeatExpansionUploadResult {
  processed: number;
  inserted: number;
  source_format: "trgt";
}

/**
 * Whether the report, as it would be signed now, matches the latest sign-out.
 *
 * ``matches`` is None when the family has never been signed out. ``changed_sections``
 * names the snapshot sections whose content differs from the signed one;
 * ``not_compared`` those the signed snapshot predates and so cannot be compared (a
 * reference module as ``modules.<key>``, e.g. ``modules.hpo``); ``not_captured`` the
 * parts the signed snapshot records as unavailable or, being older, does not hold.
 */
export interface ReportSignoutCheckOut {
  family_id: string;
  version: number | null;
  content_hash: string | null;
  matches: boolean | null;
  changed_sections: string[];
  not_compared: string[];
  not_captured: ReportSnapshotGapOut[];
  checked_at: string;
}

/** A frozen, content-hashed report snapshot. */
export interface ReportSignoutDetail {
  version: number;
  signed_out_by: string;
  signed_out_at: string;
  content_hash: string;
  software_version: string | null;
  git_sha: string | null;
  qc_status: string | null;
  qc_acknowledged: boolean | null;
  qc_acknowledgement_reason: string | null;
  drift_acknowledged: boolean | null;
  drift_acknowledgement_reason: string | null;
  import_incomplete_failed_datasets: string[] | null;
  import_incomplete_job_id: string | null;
  import_incomplete_acknowledged: boolean | null;
  import_incomplete_acknowledgement_reason: string | null;
  verified: boolean | null;
  snapshot: Record<string, unknown> | null;
  not_captured: ReportSnapshotGapOut[];
}

export interface ReportSignoutListOut {
  family_id: string;
  latest: ReportSignoutSummary | null;
  signouts: ReportSignoutSummary[];
}

/**
 * Sign out the current report.
 *
 * Evidence drift, a failing sample-integrity QC and an incomplete import (a family
 * package import that partly failed) must each be explicitly acknowledged, and each
 * acknowledgement requires a reason.
 */
export interface ReportSignoutRequest {
  acknowledge_drift?: boolean;
  drift_acknowledgement_reason?: string | null;
  acknowledge_qc?: boolean;
  qc_acknowledgement_reason?: string | null;
  acknowledge_import_incomplete?: boolean;
  import_incomplete_acknowledgement_reason?: string | null;
}

export interface ReportSignoutSummary {
  version: number;
  signed_out_by: string;
  signed_out_at: string;
  content_hash: string;
  software_version: string | null;
  git_sha: string | null;
  qc_status: string | null;
  qc_acknowledged: boolean | null;
  qc_acknowledgement_reason: string | null;
  drift_acknowledged: boolean | null;
  drift_acknowledgement_reason: string | null;
  import_incomplete_failed_datasets: string[] | null;
  import_incomplete_job_id: string | null;
  import_incomplete_acknowledged: boolean | null;
  import_incomplete_acknowledgement_reason: string | null;
  verified: boolean | null;
}

/** A part of a signed snapshot that was frozen as unavailable, and why (#514). */
export interface ReportSnapshotGapOut {
  section: string;
  item: string;
  reason: string;
}

/** NIPT category-distribution QC (de-novo / paternal-absent / maternal transmission). */
export interface SampleIntegrityCategoryQcOut {
  denovo: number;
  paternal_absent: number;
  maternal_informative: number;
  maternal_inherited: number;
  maternal_inherited_rate: number;
  status: string;
  message: string;
}

/** NIPT fetal sex from paternal X transmission (cfDNA). */
export interface SampleIntegrityFetalSexCheckOut {
  inferred_sex: string;
  x_transmitted: number;
  x_not_transmitted: number;
  informative_sites: number;
  status: string;
  message: string;
}

/** Mendelian-error rate for a child against its present parent(s). */
export interface SampleIntegrityMendelianCheckOut {
  child: string;
  parents: string[];
  informative_sites: number;
  mendel_errors: number;
  mendel_rate: number;
  status: string;
  message: string;
}

/**
 * NIPT paternity: the father's homozygous alleles must all be in the plasma, his het
 * ones half. ``cat7_transmitted`` counts both kinds seen, ``cat8_absent`` the homozygous
 * ones missing.
 */
export interface SampleIntegrityPaternityCheckOut {
  father: string;
  cat7_transmitted: number;
  cat8_absent: number;
  informative_sites: number;
  hom_alt_transmitted: number;
  hom_alt_not_transmitted: number;
  het_transmitted: number;
  het_not_transmitted: number;
  status: string;
  message: string;
}

/**
 * Per-family sample-integrity QC, adapted to the application.
 *
 * Catches sample swaps and mislabelled relationships before interpretation. The
 * checks run depend on the application (``application``): full WGS pedigrees run
 * sex + relatedness + Mendelian; PGT highlights embryo sex + parentage; NIPT runs
 * paternity (cat 7/8) instead of genotype relatedness; couples run sex (+ an
 * expected-unrelated confirmation); single samples run sex only.
 */
export interface SampleIntegrityQcOut {
  family_id: string;
  overall_status: string;
  application: string;
  application_label: string;
  application_summary: string;
  genotype_source: string | null;
  sex_checks: SampleIntegritySexCheckOut[];
  relatedness_checks: SampleIntegrityRelatednessCheckOut[];
  mendelian_checks: SampleIntegrityMendelianCheckOut[];
  paternity_check: SampleIntegrityPaternityCheckOut | null;
  fetal_sex_check: SampleIntegrityFetalSexCheckOut | null;
  category_qc_check: SampleIntegrityCategoryQcOut | null;
  autosomal_sites: number;
  notes: string[];
}

/** KING-robust relatedness for a sample pair vs the pedigree's assertion. */
export interface SampleIntegrityRelatednessCheckOut {
  sample_a: string;
  sample_b: string;
  expected_relationship: string;
  inferred_relationship: string;
  kinship: number;
  ibs0_rate: number;
  informative_sites: number;
  status: string;
  message: string;
}

/** Genotype-inferred sex vs the recorded sex for one sample. */
export interface SampleIntegritySexCheckOut {
  sample_id: string;
  recorded_sex: string;
  inferred_sex: string;
  x_het_rate: number | null;
  x_sites: number;
  status: string;
  message: string;
}

export interface SampleInventoryOut {
  sample_id: string;
  role: string;
  affected: boolean;
  sex: string;
  projects: string[];
  track_counts: Record<string, number>;
  total_records: number;
}

/** A sample's sequencing QC and its overall verdict (the worst metric). */
export interface SampleSequencingQcEvaluationOut {
  verdict: "pass" | "warn" | "fail" | "skip";
  metrics: SampleSequencingQcMetricOut[];
  breached: string[];
  profile_key: string | null;
  profile_label: string | null;
}

/** One sequencing-QC metric measured against its configured cut-offs. */
export interface SampleSequencingQcMetricOut {
  metric_key: string;
  label: string;
  unit: string;
  direction: "lower_is_worse" | "higher_is_worse";
  value: number;
  warn_value: number | null;
  error_value: number | null;
  verdict: "pass" | "warn" | "fail" | "skip";
}

export interface SegmentalDuplicationOut {
  _id: string;
  chr: string;
  start: number;
  end: number;
  label: string;
  source: string | null;
}

/** One caller signal file the genome browser can draw. */
export interface SignalTrackManifestEntryOut {
  sample_id: string;
  source: string;
  kind: string;
  name: string;
  format: "bigwig" | "bedgraph";
  url: string;
  min: number | null;
  max: number | null;
}

/**
 * Generic signup acknowledgement.
 *
 * Returned for every signup request regardless of whether the submitted email
 * is already registered, so the endpoint cannot be used to enumerate accounts.
 */
export interface SignupAck {
  detail: string;
}

export interface SmallVariantCompoundHetReviewOut {
  group_id: string;
  partner_variant_ids: string[];
  gene: string | null;
  gene_id: string | null;
  classification: string | null;
  tags: string[];
  tag_metadata: Record<string, Record<string, string | null>>;
  note: string | null;
  phase_status: string | null;
  updated_by: string | null;
  updated_at: string | null;
}

export interface SmallVariantCompoundHetReviewUpdate {
  partner_variant_id?: string | null;
  classification?: string | null;
  tags?: string[];
  note?: string | null;
}

export interface SmallVariantFilterPresetCreate {
  name: string;
  description?: string | null;
  filters?: Record<string, unknown>;
  sample_filters?: Record<string, unknown>;
  sample_templates?: Record<string, unknown>;
}

export interface SmallVariantFilterPresetOut {
  _id: string;
  owner: string;
  name: string;
  description: string | null;
  filters: Record<string, unknown>;
  sample_filters: Record<string, unknown>;
  sample_templates: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface SmallVariantGroupOut {
  group_type: "compound_het";
  group_key: string;
  gene: string | null;
  gene_id: string | null;
  variants: VariantOut[];
  review: SmallVariantCompoundHetReviewOut | null;
  phase: "trans" | "unknown";
  phase_evidence: "read" | "segregation" | null;
}

export interface SmallVariantReviewOut {
  variant_id: string;
  classification: string | null;
  tags: string[];
  tag_metadata: Record<string, Record<string, string | null>>;
  note: string | null;
  updated_by: string | null;
  updated_at: string | null;
  compound_het: SmallVariantCompoundHetReviewOut | null;
  acmg: AcmgClassificationPayload | null;
  cnv_acmg: CnvAcmgClassificationPayload | null;
  acmg_unreadable: boolean;
}

export interface SmallVariantReviewSummaryOut {
  reviewed_variant_count: number;
  note_count: number;
  tag_counts: Record<string, number>;
}

export interface SmallVariantReviewUpdate {
  expected_updated_at?: string | null;
  classification?: string | null;
  tags?: string[];
  note?: string | null;
  compound_het?: SmallVariantCompoundHetReviewUpdate | null;
  acmg?: AcmgClassificationPayload | null;
  cnv_acmg?: CnvAcmgClassificationPayload | null;
}

export interface SmallVariantSampleSummaryOut {
  sample_id: string;
  non_ref_count: number;
  het_count: number;
  hom_alt_count: number;
}

export interface SmallVariantSummaryOut {
  total_variants: number;
  snv_count: number;
  indel_count: number;
  sample_counts: SmallVariantSampleSummaryOut[];
}

export interface SmallVariantTagDefinitionCreate {
  label: string;
  description?: string | null;
  scope?: "global" | "project";
  project_id?: string | null;
  shared_project_ids?: string[];
  group?: "collaboration" | "classification" | "custom";
  color?: string;
}

export interface SmallVariantTagDefinitionOut {
  key: string;
  label: string;
  description: string | null;
  group: "collaboration" | "classification" | "custom";
  color: string;
  sort_order: number;
  scope: "system" | "global" | "project";
  project_id: string | null;
  shared_project_ids: string[];
  is_custom: boolean;
}

export interface SmallVariantTagDefinitionUpdate {
  label?: string | null;
  description?: string | null;
  scope?: "global" | "project" | null;
  project_id?: string | null;
  shared_project_ids?: string[] | null;
  group?: "collaboration" | "classification" | "custom" | null;
  color?: string | null;
}

export interface SmallVariantTranscriptOut {
  gene: string | null;
  gene_id: string | null;
  transcript_id: string | null;
  transcript_source: string | null;
  feature_type: string | null;
  transcript_biotype: string | null;
  impact: string | null;
  effect: string | null;
  hgvsc: string | null;
  hgvsp: string | null;
  exon: string | null;
  intron: string | null;
  canonical: boolean;
  mane_select: boolean;
  mane_plus_clinical: boolean;
  primary: boolean;
}

/** What a family small-variant VCF upload stored. */
export interface SmallVariantUploadResult {
  inserted: number;
  skipped_malformed: number;
  skipped_filtered: number;
  excluded_filters: string[];
  haplotypes_inserted: number;
  source_format: "clair3" | "glimpse2" | "mito";
  annotation_rows: number;
  annotation_source: string | null;
  annotation_version: string;
  annotation_provenance: Record<string, Record<string, unknown>>;
  insert_batch_size: number;
}

export interface SpeciesCreate {
  name: string;
  common_name: string;
  tax_id: number;
}

export interface SpeciesOut {
  _id: string;
  name: string;
  common_name: string;
  tax_id: number;
}

/**
 * A structural-variant / CNV classification whose frozen evidence changed since it
 * was made (services/structural_variant_evidence.py).
 */
export interface StructuralClassificationDriftItem {
  variant_id: string;
  classification: string | null;
  cnv_class: string | null;
  classified_by: string | null;
  classified_at: string | null;
  status: string;
  changed: string[];
  evidence_from: Record<string, unknown> | null;
  evidence_to: Record<string, unknown> | null;
}

/** Evidence-drift summary for a family's structural-variant / CNV classifications. */
export interface StructuralClassificationDriftOut {
  checked: number;
  drifted_count: number;
  drifted: StructuralClassificationDriftItem[];
}

/**
 * The gene of this small variant is also hit by a structural variant — the cross-type
 * "second hit" that can complete a recessive (compound-het) genotype.
 */
export interface SvSecondHitOut {
  sv_count: number;
  sv_types: string[];
  gene: string | null;
  chr: string | null;
  start: number | null;
  end: number | null;
  affected_zygosity: string | null;
  has_deletion: boolean;
  phase: string;
  phase_evidence: string | null;
  deletion_unmasked: boolean;
}

export interface Token {
  access_token: string;
  token_type: string;
  role: string;
}

export interface TrackAvailabilityOut {
  coverage: boolean;
  segments: boolean;
  coverage_sources: string[];
  segments_sources: string[];
  apcad_sources: string[];
  apcad: boolean;
  apcad_pcf: boolean;
  variants: boolean;
  small_variants: boolean;
  haplotypes: boolean;
  repeat_expansions: boolean;
}

export interface UiEventBatchIn {
  events?: UiEventIn[];
}

/** A single client-side interaction event submitted by the frontend. */
export interface UiEventIn {
  event_type: string;
  category?: string | null;
  label?: string | null;
  target_id?: string | null;
  path?: string | null;
  to_path?: string | null;
  href?: string | null;
  component?: string | null;
  session_id?: string | null;
  occurred_at?: string | null;
  detail?: Record<string, unknown> | null;
}

export interface UiEventIngestResult {
  accepted: number;
}

export interface UiEventOut {
  id: string;
  created_at: string;
  occurred_at: string | null;
  user_id: string | null;
  user_email: string | null;
  user_role: string | null;
  event_type: string;
  category: string | null;
  label: string | null;
  target_id: string | null;
  path: string | null;
  to_path: string | null;
  href: string | null;
  component: string | null;
  session_id: string | null;
  detail: Record<string, unknown>;
  remote_ip: string | null;
  user_agent: string | null;
}

export interface UiEventPageOut {
  page: number;
  page_size: number;
  total: number;
  items: UiEventOut[];
}

export interface UserCreate {
  email: string;
  password: string;
  first_name: string;
  last_name: string;
  affiliation: string;
}

export interface UserLogin {
  email: string;
  password: string;
}

export interface UserRead {
  id: string;
  username: string;
  email: string;
  first_name: string | null;
  last_name: string | null;
  affiliation: string | null;
  is_active: boolean;
  role: string;
  projects: string[];
  created_at: string;
}

/** Minimal user reference used for assignment/reviewer pickers. */
export interface UserRefOut {
  id: string;
  username: string;
  email: string;
  first_name: string;
  last_name: string;
}

export interface UserUpdate {
  is_active?: boolean | null;
  projects?: string[] | null;
}

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
}

export interface VariantCarrierFamilyGroupOut {
  family_id: string;
  family_uuid: string;
  project_id: string | null;
  project_name: string | null;
  carrier_count: number;
  samples: VariantCarrierSampleOut[];
}

export interface VariantCarrierSampleOut {
  sample_id: string;
  individual_name: string | null;
  role: string | null;
  genotype: string;
  zygosity: string;
  family_id: string;
  family_uuid: string;
  project_id: string | null;
  project_name: string | null;
  phenotype_summary: string | null;
}

export interface VariantCarriersOut {
  key: string;
  variant_id: string | null;
  total_families: number;
  total_samples: number;
  het_samples: number;
  hom_samples: number;
  truncated: boolean;
  families: VariantCarrierFamilyGroupOut[];
}

/** An assembly available to the user in the Global Small Variant Explorer. */
export interface VariantExplorerAssemblyOut {
  assembly_id: string;
  assembly_name: string;
  version: string | null;
  species_name: string | null;
  project_count: number;
}

/** Occurrence of a variant within the accessible CoGA cohort. */
export interface VariantInternalCohortOut {
  samples: number;
  het: number;
  hom: number;
  families: number;
}

/** Length of a variant with optional type and source annotations. */
export interface VariantLengthOut {
  length: number;
  type: string;
  source: string | null;
  chr: string;
}

export interface VariantOut {
  _id: string;
  chr: string;
  start: number;
  end: number;
  length: number;
  type: string;
  source: string | null;
  qual: number | null;
  read_support: number | null;
  filter: string | null;
  remote_chr: string | null;
  remote_start: number | null;
  ref: string | null;
  alt: string | null;
  ps: number | null;
  gene: string | null;
  gene_id: string | null;
  gene_symbols: string[];
  gene_count: number | null;
  transcript_id: string | null;
  feature_type: string | null;
  transcript_biotype: string | null;
  impact: string | null;
  effect: string | null;
  clinvar: string | null;
  rsid: string | null;
  hgvsc: string | null;
  hgvsp: string | null;
  canonical: boolean;
  mane_select: boolean;
  mane_plus_clinical: boolean;
  exon: string | null;
  intron: string | null;
  lof: string | null;
  lof_filter: string | null;
  lof_flags: string | null;
  gnomad_af: number | null;
  gnomad_hom_count: number | null;
  gene_pli: number | null;
  gene_missense_z: number | null;
  population_frequencies: Record<string, number>;
  cadd_raw: number | null;
  cadd_phred: number | null;
  revel: number | null;
  sift: string | null;
  polyphen: string | null;
  spliceai_ds_ag: number | null;
  spliceai_ds_al: number | null;
  spliceai_ds_dg: number | null;
  spliceai_ds_dl: number | null;
  spliceai_max: number | null;
  alpha_missense_pathogenicity: number | null;
  alpha_missense_class: string | null;
  cytoband: string | null;
  annotation_extra: Record<string, unknown>;
  transcripts: SmallVariantTranscriptOut[];
  genotypes: GenotypeOut[];
  hemizygous_in_males: boolean;
  review: SmallVariantReviewOut | null;
  internal_cohort: VariantInternalCohortOut | null;
  priority: VariantPriorityOut | null;
  sv_second_hit: SvSecondHitOut | null;
}

export interface VariantPage {
  total: number;
  total_is_estimated: boolean;
  unfiltered_total: number | null;
  unfiltered_total_is_estimated: boolean;
  count_limit: number | null;
  ranking_truncated: boolean;
  candidates_capped: boolean;
  candidate_limit: number | null;
  ranking_cached: boolean;
  ranking_computed_at: string | null;
  variants: VariantOut[];
  variant_groups: SmallVariantGroupOut[];
  summary: Record<string, Record<string, number>> | null;
  small_variant_summary: SmallVariantSummaryOut | null;
}

export interface VariantPriorityOut {
  combined_score: number;
  variant_score: number;
  pathogenicity_score: number;
  frequency_score: number;
  segregation_weight: number;
  phenotype_score: number | null;
  segregation_modes: string[];
  phenotype_gene: string | null;
  phenotype_matches: MonarchPhenotypeMatchOut[];
  rank: number | null;
}

/**
 * The running build: its semantic version and git commit (TF-18 §2).
 *
 * Shown in the app footer and on every report footer (TF-15 §1).
 */
export interface VersionOut {
  version: string;
  git_sha: string;
}
